all:
	cd ../lhs/src && make 
	cd ../stepwise && make 
	cd ../lk/build_osx && make -j4
	cd ../wex/build_osx && make -j4
	cd ../ssc/build_osx && make -j4
	cd ../SAMnt/build_osx && make -j4

clean:
	cd ../lhs/src && make clean
	cd ../stepwise && make clean
	cd ../lk/build_osx && make clean
	cd ../wex/build_osx && make clean
	cd ../ssc/build_osx && make clean
	cd ../SAMnt/build_osx && make clean
