C     Last change:  S    17 Feb 98    1:25 pm
C****************************************************************
C SUBROUTINE CHKSTR CHECKS PARAMETERS OF THE UNIFORM* AND THE
C LOGUNIFORM* DISTRIBUTIONS FOR CONSISTENCY
C
      SUBROUTINE CHKSTR(PAR,CARD)
C     INCLUDE 'KILLFILE.INC'                                            GDW-96  
      USE KILLFILE                      
C
C     INCLUDE 'PARMS.INC'                                               GDW-96  
      USE PARMS                         
C
C     These statements removed to make modules work - GDW-96
c     COMMON/STAR/NSUBOB(NINTMX),SUBINT(NINTMX+1),NINT
      USE STAR
c     COMMON/CHRCRD/CRDSTR
      USE CHRCRD
c     COMMON/OBSTR/NSTR,NOBSTR(NVAR)
      USE OBSTR
C
      CHARACTER PAR*(*),CARD*(LENC),PLOG*3
c     CHARACTER*(LENC) CRDSTR(NVAR)
      PARAMETER (PLOG='LOG')
C
      IF(NINT.EQ.0)THEN
        WRITE(6,9001)PAR
        WRITE(99,9001)PAR
        KLLERR = .TRUE.
        RETURN
C
      ELSE IF(NINT.GT.NINTMX)THEN
        WRITE(6,9002)PAR,NINT,NINTMX
        WRITE(99,9002)PAR,NINT,NINTMX
        KLLERR = .TRUE.
        RETURN
C
      ELSE
        WRITE(8)NINT
C
      ENDIF
C
      NSTR=NSTR+1
      DO 100 I=1,NINT
C
        IF(PAR(1:3).EQ.PLOG.AND.SUBINT(I).LE.0.0)THEN
          WRITE(6,9003)PAR,I,SUBINT(I)
          WRITE(99,9003)PAR,I,SUBINT(I)
          KLLERR = .TRUE.
          RETURN
C
        ELSE IF(SUBINT(I).GE.SUBINT(I+1))THEN
          WRITE(6,9004)PAR,I,SUBINT(I),SUBINT(I+1)
          WRITE(99,9004)PAR,I,SUBINT(I),SUBINT(I+1)
          KLLERR = .TRUE.
          RETURN
C
        ELSE IF(NSUBOB(I).LT.0)THEN
          WRITE(6,9005)PAR,I
          WRITE(99,9005)PAR,I
          KLLERR = .TRUE.
          RETURN
C
        ELSE
          NOBSTR(NSTR)=NOBSTR(NSTR)+NSUBOB(I)
          WRITE(8)NSUBOB(I),SUBINT(I),SUBINT(I+1)
C
        ENDIF
C
  100 CONTINUE
C
      CRDSTR(NSTR)=CARD
C
      RETURN
C
 9001 FORMAT('1',5X,'FOR THE ',A,'DISTRIBUTION THE NUMBER OF ',
     1       'SUBINTERVALS IS ZERO')
 9002 FORMAT('1',5X,'FOR THE ',A,'DISTRIBUTION THE NUMBER OF ',
     1       'SUBINTERVALS REQUESTED ',I3,/,6X,'IS GREATER THAN THE ',
     2       'MAXIMUM NUMBER OF SUBINTERVALS CURRENTLY PERMITTED ',I3,
     3       /,6X,'PLEASE CONSULT THE USER MANUAL FOR INSTRUCTIONS ',
     4       'ON HOW TO ALLOW MORE SUBINTERVALS')
 9003 FORMAT('1',5X,'FOR THE ',A,'DISTRIBUTION THE SUBINTERVAL ',
     1       'LIMIT FOR SUBINTERVAL ',I3,/,6X,'IS LESS THAN OR ',
     2       'EQUAL TO ZERO ',G20.10)
 9004 FORMAT('1',5X,'ON THE ',A,'DISTRIBUTION FOR SUBINTERVAL ',
     1       I3,' THE LOWER LIMIT ',G20.10,/,6X,'IS GREATER ',
     2       'THAN OR EQUAL TO THE UPPER LIMIT ',G20.10)
 9005 FORMAT('1',5X,'FOR THE ',A,'DISTRIBUTION SUBINTERVAL ',I3,
     1       ' REQUESTED A NEGATIVE NUMBER OF OBSERVATIONS')
C
      END
