#include "tcstype.h"

TCS_DEFINE_TYPE( weatherreader )
TCS_DEFINE_TYPE( trnsys_weatherreader )
TCS_DEFINE_TYPE( solarcollector )
TCS_DEFINE_TYPE( pump )
TCS_DEFINE_TYPE( datatest )
TCS_DEFINE_TYPE( sumprod )
TCS_DEFINE_TYPE( sco2_test_type401 )
TCS_DEFINE_TYPE( sam_sco2_recomp_type424 )
TCS_DEFINE_TYPE( tc_test_type402 )
TCS_DEFINE_TYPE( sam_trough_model_type805 )
TCS_DEFINE_TYPE( sam_trough_plant_type807 )
TCS_DEFINE_TYPE( sam_trough_storage_type806 )
TCS_DEFINE_TYPE( sam_mw_pt_type224 )
TCS_DEFINE_TYPE( sam_mw_trough_type250 )
TCS_DEFINE_TYPE( sam_type250_input_generator )
TCS_DEFINE_TYPE( sam_mw_trough_type251 )
TCS_DEFINE_TYPE( sam_mw_csp_SumCalcs )
TCS_DEFINE_TYPE( sam_mw_pt_type221 )
TCS_DEFINE_TYPE( sam_mw_pt_heliostatfield )
TCS_DEFINE_TYPE( sam_lf_st_pt_type232 )
TCS_DEFINE_TYPE( sam_mw_pt_type222 )
TCS_DEFINE_TYPE( sam_dsg_controller_type265 )
TCS_DEFINE_TYPE( sam_mw_gen_type260 )
TCS_DEFINE_TYPE( sam_mw_lf_type262 )
TCS_DEFINE_TYPE( sam_mw_type234 )
TCS_DEFINE_TYPE( sam_mw_pt_type228 )
TCS_DEFINE_TYPE( sam_pf_dish_collector_type295 )
TCS_DEFINE_TYPE( sam_pf_dish_receiver_type296 )
TCS_DEFINE_TYPE( sam_pf_dish_engine_type297 )
TCS_DEFINE_TYPE( sam_pf_dish_parasitics_type298 )
TCS_DEFINE_TYPE( sam_mw_lf_type261_steam )
TCS_DEFINE_TYPE( sam_iscc_powerblock )
TCS_DEFINE_TYPE( sam_iscc_parasitics )
TCS_DEFINE_TYPE( sam_mw_lf_type261_Wnet )
TCS_DEFINE_TYPE( tou_translator )
TCS_DEFINE_TYPE( atmospheric_aod )
TCS_DEFINE_TYPE( Heliostat3DInterp )
//TCS_DEFINE_TYPE( sam_geothermal_hybrid_pb )

TCS_BEGIN_EXPORT()
	TCS_EXPORT_TYPE( weatherreader )
	TCS_EXPORT_TYPE( trnsys_weatherreader )
	TCS_EXPORT_TYPE( solarcollector )
	TCS_EXPORT_TYPE( pump )
	TCS_EXPORT_TYPE( datatest )
	TCS_EXPORT_TYPE( sumprod )
	TCS_EXPORT_TYPE( sco2_test_type401 )
	TCS_EXPORT_TYPE( sam_sco2_recomp_type424 )
	TCS_EXPORT_TYPE( tc_test_type402 )
	TCS_EXPORT_TYPE( sam_trough_model_type805 )
	TCS_EXPORT_TYPE( sam_trough_plant_type807 )
	TCS_EXPORT_TYPE( sam_trough_storage_type806 )
	TCS_EXPORT_TYPE( sam_mw_pt_type224 )
	TCS_EXPORT_TYPE( sam_mw_trough_type250 )
	TCS_EXPORT_TYPE( sam_type250_input_generator )
	TCS_EXPORT_TYPE( sam_mw_trough_type251 )
	TCS_EXPORT_TYPE( sam_mw_csp_SumCalcs )
	TCS_EXPORT_TYPE( sam_mw_pt_type221 )
	TCS_EXPORT_TYPE( sam_mw_pt_heliostatfield )
	TCS_EXPORT_TYPE( sam_lf_st_pt_type232 )
	TCS_EXPORT_TYPE( sam_mw_pt_type222 )
	TCS_EXPORT_TYPE( sam_mw_gen_type260 )
	TCS_EXPORT_TYPE( sam_dsg_controller_type265 )
	TCS_EXPORT_TYPE( sam_mw_lf_type262 )
	TCS_EXPORT_TYPE( sam_mw_type234 )
	TCS_EXPORT_TYPE( sam_mw_pt_type228 )
	TCS_EXPORT_TYPE( sam_pf_dish_collector_type295 )
	TCS_EXPORT_TYPE( sam_pf_dish_receiver_type296 )
	TCS_EXPORT_TYPE( sam_pf_dish_engine_type297 )
	TCS_EXPORT_TYPE( sam_pf_dish_parasitics_type298 )
	TCS_EXPORT_TYPE( sam_mw_lf_type261_steam )
	TCS_EXPORT_TYPE( sam_iscc_powerblock )
	TCS_EXPORT_TYPE( sam_iscc_parasitics )
	TCS_EXPORT_TYPE( sam_mw_lf_type261_Wnet )
	TCS_EXPORT_TYPE( tou_translator )
	TCS_EXPORT_TYPE( atmospheric_aod )
	TCS_EXPORT_TYPE( Heliostat3DInterp )
	//TCS_EXPORT_TYPE( sam_geothermal_hybrid_pb )
TCS_END_EXPORT()




