pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["3d-scene.htm","3D Scene","3D Scene The 3D scene view gives you a three-dimensional representation of the scene. Use it to: Add shading and active surface objects to the sce...",""],
["active-surface.htm","Add active surface objects","Add active surface objects An active surface object is a rectangular shape that represents the photovoltaic array or subarray. You can add as many...",""],
["analyze.htm","Analyze","Analyze Click Analyze after create the shading scene to generate shading data. You can then export shading data for use in simulation models and o...",""],
["beta.htm","Beta Test Information","Beta Test Information This version of the SAM Shade Calculator is a Beta version for testing. During the Beta test period, we are collecting feedb...",""],
["birds-eye.htm","Bird&#39;s Eye","Bird&#39;s Eye The bird&#39;s eye view gives you an overhead view of the scene and allows you to change object sizes and positions in the X-Y plane. In th...",""],
["change-view.htm","Change the view","Change the view You can display the scene in three different views: 3D scene shows a three-dimensional representation of the objects in the scene....",""],
["colors.htm","Change object colors","Change object colors You can change the color of box and roof objects in any view. To change an object&#39;s color 1. Select the box or roof. 2. In th...",""],
["create.htm","Create (Shape Reference)","Create (Shape Reference) The Create list allows you to add shading objects and active surface objects to the scene. Active Surface An active surfa...",""],
["define-location.htm","Define the scene location","Define the scene location The scene location consists of a latitude, longitude, and time zone. The shade calculator requires this information to c...",""],
["delete.htm","Delete and copy objects","Delete and copy objects You can delete and copy objects from any view. Note. The SAM shade calculator does not have an Undo feature. To delete an ...",""],
["elevations.htm","Elevations","Elevations The elevations view gives you a view of the scene from the south. In this view you can: Zoom and pan the scene . Use an image underlay ...",""],
["export.htm","Export shade data","Export shade data You can export shade data to use in SAM or with other software. To export diurnal data 1. Click Analyze. 2. Generate the shade d...",""],
["file-types.htm","File Types","File Types The shade calculator works with the following types of files: Shade scene files, .s3d Shade scene files are binary files that store inf...",""],
["generate-data.htm","Generate shading data","Generate shade data Once you have created a scene with shading objects and active objects, you can generate tables of shade fractions: Diurnal tab...",""],
["how-to.htm","How-To","How-To The How-To section describes the shade calculator by task: Define the scene location Use an image underlay Add shading objects Add active s...",""],
["location.htm","Location","Location The Location page is where you define the scene location with an option to use an image underlay . Address The street address for the sce...",""],
["move.htm","Move objects","Move objects You can move objects by either dragging handles (magenta circles) with your mouse, or typing values for the object properties. You ca...",""],
["open-save.htm","Open and Save","Open and Save A .s3d file is a binary file that stores information describing the shading scene. To open a .s3d file 1. Click Open to open the Loa...",""],
["overview.htm","Overview","Overview The SAM Shade Calculator uses a sun position algorithm and a three-dimensional drawing of a photovoltaic array and nearby shading objects...",""],
["proxy.htm","Configure proxy server","Configure proxy server By default, the shade calculator&#39;s location tools use your computer’s default internet access settings to communicate with ...",""],
["reference.htm","Reference","Reference This section describes the shade calculator by feature and view: Open and Save Location Create (Shape Reference) 3D Scene Bird&#39;s Eye Ele...",""],
["resize.htm","Resize objects","Resize objects You can resize objects by either dragging handles (pink circles) with your mouse, or typing values for the object properties. You c...",""],
["rotate.htm","Rotate objects","Rotate objects You can rotate rectangular objects in the horizontal plane. In bird&#39;s eye view, drag the rotation handle, or in any view change the...",""],
["sam.htm","Use shade data in SAM","Use shade data in SAM The System Advisor Model (SAM) photovoltaic models (Flat Plate PV and PVWatts System) can import diurnal and hourly shade da...",""],
["select.htm","Select an object","Select an object Select an object when you want to move or resize it. Selected objects appear magenta in 3D scene view, and with magenta handles i...",""],
["shading-objects.htm","Add shading objects","Add shading objects A shading object is a box, cylinder, roof, round tree, or conical tree shape that represents an object near the photovoltaic a...",""],
["shortcuts.htm","Shortcuts","Shortcuts The following keyboard and mouse shortcuts make it easier to zoom and pan the scene. Note. The scene must have focus for these shortcuts...",""],
["underlay.htm","Use an image underlay","Use an image underlay You can add an optional image underlay to the bird&#39;s eye view to help you position objects more accurately. You can either a...",""],
["zoom-pan.htm","Zoom and pan the scene","Zoom and pan the scene Use your mouse and keyboard to position the scene in the window. Note: The size of the green rectangle representing the gro...",""]];
