all:
	make -f Makefile-shared -j7
	make -f Makefile-nlopt -j7
	make -f Makefile-lpsolve -j7
	make -f Makefile-solarpilot -j7
	make -f Makefile-tcs -j7
	make -f Makefile-ssc -j7
	make -f Makefile-sdktool -j7
	make -f Makefile-tcsconsole -j7 

clean:
	make -f Makefile-shared clean
	make -f Makefile-nlopt clean
	make -f Makefile-lpsolve clean
	make -f Makefile-solarpilot clean
	make -f Makefile-tcs clean
	make -f Makefile-ssc clean
	make -f Makefile-sdktool clean
	make -f Makefile-tcsconsole clean
