/* Project settings */
var hmAnimate = true;
var hmPopupSticky = true;
var hmImageLightbox = true;
var hmVideoLightbox = true;
var hmLightboxConstrained = true;
var hmForceRedirect = true;
var hmTocSingleClick = true;
var autocollapse = true;
var gaaccount = "";
var initialtocstate = "collapsed";
