
// WARNING: DO NOT EDIT THIS FILE.
// This file is automatically generated by the Zoom Indexer application
// and will be updated each time you re-index your site. You should make all
// setting changes directly from the Indexer, via the Configuration window.
// 
// If you wish to modify the text messages such as "Search results for...",
// etc. then look up "Zoom Language Files" or "Translating the search page"
// in the Users Guide for information.

var UseUTF8 = 1;
var Charset = "UTF-8";
var UseStemming = 0;
var NoCharset = 0;
var MapAccents = 0;
var MinWordLen = 3;
var Highlighting = 1;
var GotoHighlight = 1;
var PdfHighlight = 0;
var FormFormat = 2;
var Logging = 0;
var LogFileName = "./logs/searchwords.log";
var MaxKeyWordLineLen = 0;
var OutputBasewordBufferSize = 0;
var OutputVariantBufferSize = 0;
var DictIDLen = 4;
var UseBigPageInfoData = 0;
var NumKeywords = 7670;
var NumVariants = 1893;
var NumPages = 312;
var DictArrayCount = 0;
var PageInfoArrayCount = 0;
var PageDataArrayCount = 0;
var PageInfoSize = 0;
var MaxMatches = 1000;
var MaxContextSeeks = 500;
var MaxSearchTime = 30;
var MaxResultsPerQuery = 1000;
var DictReservedLimit = 165;
var DictReservedSuffixes = 83;
var DictReservedPrefixes = 124;
var DictReservedNoSpaces = 165;
var PluginOpenNewWindow = 0;
var FileTypePluginStart = 4;
var WordSplit = 1;
var ZoomInfo = 0;
var Timing = 0;
var DefaultToAnd = 1;
var SearchAsSubstring = 1;
var ToLowerSearchWords = 1;
var StripDiacritics = 0;
var ContextSize = 30;
var MaxContextKeywords = 3;
var WeightProximity = 0;
var AllowExactPhrase = 0;
var UseLinkTarget = 1;
var LinkTarget = "hmcontent";
var UseDateTime = 0;
var DateRangeSearch = 0;
var UseDomainDiversity = 1;
var DefaultSort = 0;
var DateRangeFormat = 0;
var DotNetUseFormTags = 0;
var DotNetUsePostBacks = 1;
var UseZoomImage = 0;
var WordJoinChars = ".-_'­";
var Spelling = 0;
var Recommended = 0;
var NumRecommended = 0;
var RecommendedMax = 0;
var UseCats = 0;
var UseMetaFields = 0;
var NumMetaFields = 0;
var DisplayMetaFields = 0;
var TruncateShowURL = 0;
var DisplayNumber = 1;
var DisplayTitle = 1;
var DisplayMetaDesc = 1;
var DisplayContext = 0;
var DisplayTerms = 1;
var DisplayScore = 1;
var DisplayURL = 0;
var DisplayDate = 0;
var DisplayFilesize = 0;
var StartPtFailed = 0;
var Version = "Version 7.0.1022b (Custom for EC Software) PRO";
