pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["about_sam.htm","About SAM","About SAM The System Advisor Model (SAM) is a performance and financial model designed to facilitate decision making for people involved in the re...",""],
["advanced_topics.htm","Advanced Modeling Topics","Advanced Modeling Topics Advanced topics include the following features: Libraries : View SAM&#39;s parameter databases, and add custom parameter data...",""],
["base_case_cashflow.htm","Cash Flows","Cash Flows The Cash Flows table displays the project cash flow calculated by the financial model. The Cash Flows table only displays data from the...",""],
["base_case_time_series.htm","Time Series","Time Series The Time Series viewer on the Results page displays time series data from the performance model, and time-dependent pricing data from ...",""],
["biopower.htm","Biomass Power","Biomass Power The biopower model is a performance- and cost-modeling tool for assessing the biomass power resource of a location. For a basic desc...",""],
["biopower_emissions_comparison.htm","Biopower Life-Cycle Impacts","Life-Cycle Emissions The Life-Cycle Impacts page allows you to specify inputs for a set of life-cycle greenhouse gas emissions calculations for th...",""],
["biopower_feedstock.htm","Biopower Feedstock","Feedstock The Feedstock page inputs define the biomass resource of the location you specify on the Location and Ambient Conditions page, and the p...",""],
["biopower_feedstock_costs.htm","Biopower Feedstock Costs","Biopower Feedstock Costs Biomass feedstock costs vary widely over distance, season, geographical location, type, and availability. Additionally, f...",""],
["biopower_overview.htm","Biopower Overview","Biopower Overview The biopower model is a performance- and cost-modeling tool for assessing the biomass power resource of a location. SAM can mode...",""],
["biopower_plant_specs.htm","Biopower Plant Specs","Plant Specs The Plant Specs page inputs define the major unit operations that make up a biomass power plant: biomass processing, combustion system...",""],
["biopower_system_costs.htm","Biopower System Costs","Biopower System Costs SAM uses the variables on the Biopower System Costs page to calculate the project investment cost and annual operating costs...",""],
["cash_flow_variables.htm","Cash Flow Variables","Cash Flow Variables SAM displays the cash flow variables in the Cash Flows table on the Results page , and Tables . Note. If you are looking for t...",""],
["cf_all_equity_partnership_flip.htm","Cash Flow: All Equity Partnership Flip","Cash Flow: All Equity Partnership Flip This topic describes the cash flow table generated by the financial model for the Utility All Equity Partne...",""],
["cf_ipp_commercial_ppa.htm","Cash Flow: IPP and Commercial PPA","Cash Flow: IPP and Commercial PPA This topic describes the cash flow table generated by the financial model for the Utility IPP and Commercial PPA...",""],
["cf_leveraged_partership_flip.htm","Cash Flow: Leveraged Partnership Flip","Cash Flow: Leveraged Partnership Flip (DRAFT) This topic describes the cash flow table generated by the financial model for the Utility Leveraged ...",""],
["cf_residential_and_commercial.htm","Cash Flow: Residential and Commercial","Cash Flow: Residential and Commercial This topic describes the cash flow table generated by the financial model for the residential and commercial...",""],
["cf_sale_leaseback.htm","Cash Flow: Sale Leaseback","Cash Flow: Sale Leaseback (DRAFT) This topic describes the cash flow table generated by the financial model for the Utility Sale Leaseback financi...",""],
["cf_single_owner.htm","Cash Flow: Single Owner","Cash Flow: Single Owner This topic describes the cash flow table generated by the financial model for the Utility Single Owner financing option. S...",""],
["climate_biopower.htm","Location and Ambient Conditions","Location and Ambient Conditions The Location and Ambient Conditions page allows you to choose a weather file to specify ambient conditions for the...",""],
["climate_geothermal.htm","Ambient Conditions","Ambient Conditions The Ambient Conditions page allows you to choose a weather file to specify ambient conditions for the geothermal system&#39;s power...",""],
["climate_solar.htm","Location and Resource","Location and Resource The Location and Resource page allows you to choose a weather file describing the solar resource at the project location. No...",""],
["co-production_costs.htm","Geothermal Co-Production Costs","Co-Production Costs Geothermal co-production costs are divided into two categories: Direct capital costs, and other costs. The direct capital cost...",""],
["component_models_databases.htm","Component Models and Databases","Component Models and Databases This topic lists all of SAM&#39;s performance models and describes the component-level models and databases SAM uses. S...",""],
["concentrating_solar_power_csp.htm","Concentrating Solar Power","Concentrating Solar Power The Concentrating Solar Power (CSP) technologies that SAM can model are: Parabolic Trough (Physical) Parabolic Trough (E...",""],
["depreciation.htm","Depreciation","Depreciation To view the Depreciation page, click Depreciation in the main windows navigation menu. Note. The Depreciation page is not available f...",""],
["dishstirling_overview.htm","Dish Stirling Overview","Dish Stirling Overview A dish-Stirling system is a type of concentrating solar power (CSP) system that consists of a parabolic dish-shaped collect...",""],
["dish_collector.htm","Dish Collector","Collector To view the Collector page, click Collector on the main window&#39;s navigation menu. Note that for the dish input pages to be available, th...",""],
["dish_parasitics.htm","Dish Parasitics","Parasitics To view the Parasitics Costs page, click Parasitics on the main window&#39;s navigation menu. Note that for the dish input pages to be avai...",""],
["dish_receiver.htm","Dish Receiver","Receiver To view the Receiver page, click Receiver on the main window&#39;s navigation menu. Note that for the dish input pages to be available, the t...",""],
["dish_reference_inputs.htm","Dish Reference Inputs","Reference Inputs To view the Reference Inputs page, click Reference Inputs on the main window&#39;s navigation menu. Note that for the dish input page...",""],
["dish_solar_field.htm","Dish Solar Field","Solar Field To view the Solar Field page, click Solar Field on the main window&#39;s navigation menu. Note that for the dish input pages to be availab...",""],
["dish_stirling.htm","Dish Stirling","Dish Stirling A dish-Stirling system consists of a parabolic dish-shaped collector, receiver and Stirling engine. The collector focuses direct nor...",""],
["dish_stirling_engine.htm","Dish Stirling Engine","Stirling Engine To view the Stirling Engine page, click Stirling Engine on the main window&#39;s navigation menu. Note that for the trough input pages...",""],
["dish_system_costs.htm","Dish System Costs","Dish System Costs To view the Dish System Costs page, click Dish System Costs on the main window&#39;s navigation menu. Note that for the dish input p...",""],
["dish_system_library.htm","Dish System Library","System Library To view the System Library page, click System Library on the main window&#39;s navigation menu. Note that for the dish input pages to b...",""],
["electric_load.htm","Electric Load","Electric Load The Electric Load page allows you to specify the electric load for systems with either the Residential or Commercial financing optio...",""],
["excel_exchange.htm","Excel Exchange","Excel Exchange SAM allows you to connect any input variable in SAM to a cell or range of cells in a Microsoft Excel workbook. This feature allows ...",""],
["export_data.htm","Export Data and Graphs","Export Data and Graphs SAM provides several options for exporting data and graph images to other applications for further analysis or inclusion in...",""],
["file_formats.htm","File Formats","File Formats SAM uses the following types of files to store and transfer data. The file formats are listed below by file extension in alphabetical...",""],
["financial_metrics.htm","Financial Metrics","Financial Metrics SAM displays financial metrics on the Results page after running simulations. For a general description of the Metrics table, se...",""],
["financing_models.htm","Financial Models","Financial Models SAM&#39;s financial models calculate project cash flows and financial metrics for the financing option you choose in the Technology a...",""],
["fin_all_equity_partnership.htm","Financing Page: Utility All Equity Partnership Flip","Financing: Utility All Equity Partnership Flip This topic describes the inputs on the Financing page for the Utility All Equity Partnership Flip f...",""],
["fin_annual_performance.htm","Performance Adjustment","Performance Adjustment To view the Performance Adjustment page, click Performance Adjustment in the main windows navigation menu. The Performance ...",""],
["fin_commercial.htm","Financing Page: Commercial","Financing: Commercial This topic describes the inputs on the Financing page for the Commercial financing option. For a general description of fina...",""],
["fin_energy_payment_dispatch.htm","Time of Delivery Factors","Time of Delivery Factors The Time of Delivery Factors page allows you to specify a set of time-of-delivery (TOD) factors to model time-dependent p...",""],
["fin_ipp_and_commercial_ppa.htm","Financing Page: Utility IPP and Commercial PPA","Financing: Utility IPP and Commercial PPA This topic describes the inputs on the Financing page for the Utility IPP and Commercial PPA financing o...",""],
["fin_leveraged_partnership.htm","Financing Page: Utility Leveraged Partnership Flip","Financing: Utility Leveraged Partnership Flip This topic describes the inputs on the Financing page for the Utility Leveraged Partnership Flip fin...",""],
["fin_overview.htm","Financing Overview","Financing Overview SAM&#39;s financial models calculate a project&#39;s cash flow over an analysis period that you specify. The cash flow captures the val...",""],
["fin_residential.htm","Financing Page: Residential","Financing: Residential This topic describes the inputs on the Financing page for the Residential financing option. For a general description of fi...",""],
["fin_sale_leaseback.htm","Financing Page: Utility Sale Leaseback","Financing: Utility Sale Leaseback This topic describes the inputs on the Financing page for the Utility Sale Leaseback financing option. For a gen...",""],
["fin_single_owner.htm","Financing Page: Utility Single Owner","Financing: Utility Single Owner This topic describes the inputs on the Financing page for the Utility Single Owner financing option. For a general...",""],
["generate_reports.htm","Generate Reports","Generate Reports SAM&#39;s report generator creates a PDF file that may include the following: Values of input and results variables. Values calculate...",""],
["generic_solar_system.htm","Generic Solar System","Generic Solar System The generic solar system model allows you to model a system that consists of a solar field, power block with a conventional s...",""],
["generic_system.htm","Generic System","Generic System The generic system model allows you to represent a power plant using a simple model based on capacity factor and nameplate capacity...",""],
["generic_system_costs.htm","Generic System Costs","Generic System Costs To view the Generic System Costs page, click Generic System Costs on the main window&#39;s navigation menu. Note that for the gen...",""],
["generic_system_overview.htm","Generic System Overview","Generic System Overview The generic system model allows you to represent a power plant using a simple model based on capacity factor and nameplate...",""],
["generic_system_plant.htm","Power Plant","Power Plant The Power Plant page allows you to specify the electricity output of the generic power system either as a nameplate capacity and capac...",""],
["geothermal.htm","Geothermal","Geothermal SAM&#39;s geothermal models include: Geothermal Power Geothermal Co-production For an overview of all technologies, see Technology Options . ",""],
["geothermal_co-production.htm","Geothermal Co-production","Geothermal Co-production The Geothermal Co-Production model estimates power output from co-production resources based on the resource temperature ...",""],
["geothermal_power_overview.htm","Geothermal Power Overview","Geothermal Power Overview SAM&#39;s geothermal power model is based on the U.S. Department of Energy&#39;s Geothermal Electricity Technology Evaluation Mo...",""],
["geo_geothermal_resource.htm","Geothermal Resource","Geothermal Resource Resource Characterization The resource characterization inputs describe the energy available in the underground geology at the...",""],
["geo_overview.htm","Geothermal Power","Geothermal Power The geothermal power plant model calculates the output of a power plant that uses heat from below the surface of the ground to dr...",""],
["geo_plant_equipment.htm","Geothermal Plant and Equipment","Plant and Equipment Note. This topic is still under development. For more details about SAM&#39;s geothermal model, please refer to the documentation ...",""],
["geo_power_block.htm","Geothermal Power Block","Power Block The Power Block page allows you to specify the parameters of a power block that converts thermal energy from the geothermal resource t...",""],
["geo_system_costs.htm","Geothermal System Costs","Geothermal System Costs As will all of the SAM models, the cost page is used to calculate a total installed cost and an operating cost for use in ...",""],
["getting_started.htm","Getting Started","Getting Started The Getting Started topics introduce you to SAM: Start a Project describes the steps for creating a SAM file. Welcome Page describ...",""],
["graphs_and_charts.htm","Graphs","Graphs SAM displays graphs on the Results page after running simulations. The standard graphs that appear by default show summaries of results fro...",""],
["gss_overview.htm","Generic Solar Overview","Generic Solar Overview The generic solar system model allows you to model a system that consists of a solar field, power block with a conventional...",""],
["gss_power_block.htm","Generic Solar Power Block","Power Block Capacity Design gross output (MWe) The power cycle&#39;s design output, not accounting for parasitic losses. SAM uses this value to size s...",""],
["gss_solar_field.htm","Generic Solar Solar Field","Solar Field Input Variable Reference Solar Field Optical Efficiency Data The solar position table option allows you to specify optical efficiency ...",""],
["gss_system_costs.htm","Generic Solar System Costs","Generic Solar System (GSS) Costs CSP System Cost Notes. The default cost values that appear when you create a file or case are intended to illustr...",""],
["gss_thermal_storage.htm","Generic Solar Thermal Storage","Thermal Storage Thermal Energy Storage (TES) Full Load Hours of TES The thermal storage capacity expressed in number of hours of thermal energy de...",""],
["hcpv_array.htm","Array","Array The Concentrating Array page displays inputs for the High-X Concentrating PV performance model. SAM assumes that HCPV modules are mounted on...",""],
["hcpv_inverter.htm","Inverter","Inverter The Sandia Performance Model for Grid-Connected PV Inverters is an empirically-based performance model that uses parameters from a databa...",""],
["hcpv_module.htm","Module","Module The HCPV Module page inputs are for the High-X Concentrating PV performance model. High Concentration Photovoltaic (HCPV) Module Single cel...",""],
["hcpv_system_costs.htm","HCPV Costs","HCPV Costs The HCPV System Costs page provides access to variables that define the installation and operating costs of a high-X concentrating PV p...",""],
["incentives.htm","Incentives","Incentives To view the Incentives page, click Incentives in the main windows navigation menu. The Incentives page allows you to define the paramet...",""],
["input_pages.htm","Input Pages","Input Pages An input page is where you specify input variable values and options. SAM&#39;s input pages provide access to the input variables and opti...",""],
["introduction.htm","Introduction","Introduction The System Advisor Model (SAM) is a performance and financial model for renewable energy power systems and projects. For a general de...",""],
["keep_up_to_date.htm","Keep SAM Up to Date","Keep SAM Up to Date SAM Versions The SAM team releases new versions of SAM periodically. To find out if your version of SAM is the latest version,...",""],
["lf_collector_and_receiver.htm","Collector and Receiver","Collector and Receiver Linear Fresnel Boiler Geometry / Superheater Geometry This dropdown specifies whether the collector and receiver geometry d...",""],
["lf_overview.htm","Linear Fresnel Overview","Linear Fresnel Overview The Linear Fresnel model predicts the performance of a direct-steam generation (DSG) plant that produces superheated steam...",""],
["lf_parasitics.htm","Parasitics","Parasitics The parameters on the Parasitics page describe parasitic electrical loads and other losses in the linear fresnel system. Page numbers r...",""],
["lf_power_cycle.htm","Power Cycle","Power Cycle The power cycle converts thermal energy to electric energy. The power cycle is assumed to consist of a superheated two-stage turbine w...",""],
["lf_solar_field.htm","Solar Field","Solar Field Input Variable Reference Solar Field Parameters Option 1 and Option 2 For Option 1 (solar multiple mode), SAM calculates the total req...",""],
["libraries.htm","Libraries","Libraries A library is a collection of stored values for groups of input variables that characterize a system component, heat transfer fluid, or f...",""],
["linear_fresnel.htm","Linear Fresnel","Linear Fresnel The Linear Fresnel model predicts the performance of a direct-steam generation (DSG) plant that produces superheated steam at tempe...",""],
["linear_fresnel_system_costs.htm","Linear Fresnel System Costs","Linear Fresnel System Costs SAM uses the variables on the Linear Fresnel Costs page to calculate the project investment cost and annual operating ...",""],
["loss_diagram.htm","Loss Diagram","Loss Diagram SAM displays a Sankey diagram showing the energy at different points in the system, and the source of energy losses at each point. To...",""],
["main_window.htm","Main Window","Main Window The main window gives you access to the input pages for each of the cases in the project: The case tabs display different cases in the...",""],
["manage_cases.htm","Manage Cases","Manage Cases A case is a complete set of input data and results. A project file contains at least one case. SAM uses tabs to display each case in ...",""],
["menus.htm","Menus","Menus SAM&#39;s menus provide access to commands for managing projects, running simulations, exporting results, and getting more information about the...",""],
["metrics_table.htm","Metrics Table","Metrics Table The Metrics table on the Results page displays a selected set of results variables for each case in the project file. For a list and...",""],
["mtf_costs.htm","Project Costs","Project Costs For the advanced utility IPP financing options, SAM displays some key cost metrics on the Results page for convenience in assessing ...",""],
["mtf_debt_and_equity.htm","Debt and Equity","Debt and Equity For the advanced utility IPP financing options that include debt (single owner and leveraged partnership flip), SAM displays the t...",""],
["mtf_debt_fraction.htm","Debt Fraction","Debt Fraction The debt fraction is the project debt amount as percentage of the total project cost. For example, a debt fraction of 25% means that...",""],
["mtf_financing_cost.htm","Financing Cost","Financing Cost The financing cost is reported on the Results page for the advanced utility financing options. The financing cost is the sum of the...",""],
["mtf_irr.htm","Internal Rate of Return ","Internal Rate of Return (IRR) The internal rate of return is the nominal discount rate that corresponds to a net present value of zero for project...",""],
["mtf_land_area.htm","Land Area","Land Area For some of the performance models, SAM reports an estimate of the land area required for the project. SAM uses the value to calculate a...",""],
["mtf_lcoe.htm","Levelized Cost of Energy (LCOE)","Levelized Cost of Energy (LCOE) The LCOE is the total cost of installing and operating a project expressed in dollars per kilowatt-hour of electri...",""],
["mtf_minimum_dscr.htm","Minimum DSCR","Minimum DSCR The minimum DSCR is the minimum debt-service coverage ratio that SAM calculates for projects with the Commercial PPA or Utility IPP f...",""],
["mtf_npv.htm","Net Present Value (NPV)","Net Present Value (NPV) A project&#39;s net present value (NPV) is a measure of a project&#39;s economic feasibility that includes both revenue (or saving...",""],
["mtf_overview.htm","Financial Metrics Overview","Financial Metrics Overview The financial metrics are selected single-value results from the financial models and performance models. After running...",""],
["mtf_payback.htm","Payback Period","Payback Period The payback period is the time in years that it takes for project savings in years two and later of the cash flow described below t...",""],
["mtf_ppa_escalation.htm","PPA Price Escalation","PPA Price Escalation The PPA escalation rate is an annual escalation rate that SAM uses to calculate the PPA price in Years Two and later of the c...",""],
["mtf_ppa_price.htm","PPA Price","PPA Price The PPA price is the power purchase bid price for projects with one of the Utility financing options, or with the Commercial PPA financi...",""],
["mtf_real_estate_added_value.htm","Real Estate Value Added","Real Estate Value Added The real estate value added is an annual dollar amount that SAM calculates for the residential and commercial financing op...",""],
["mtf_revenues.htm","Electricity Cost and Savings","Electricity Cost and Savings For the residential and commercial financing options, SAM assumes that electricity generated by the system displaces ...",""],
["mtp_annual_biomass_usage.htm","Annual Biomass Usage","Annual Biomass Usage For the biomass power model, Annual Biomass Usage is the annual biomass feedrate, equal to the total obtainable biomass resou...",""],
["mtp_annual_energy.htm","Annual Energy","Annual Energy SAM reports the total quantity of electricity generated by the system in Year one of the project cash flow and reports it in the Met...",""],
["mtp_annual_water_usage.htm","Annual Water Usage","Annual Water Usage For physical trough, power tower, and linear Fresnel systems, SAM reports the total annual water consumption in cubic meters fo...",""],
["mtp_aux_w_wo_solar.htm","Aux with and without Solar (kWh)","Aux with and without Solar (kWh) The Solar Water Heating Model calculates the annual energy savings by a solar water heating system designed to me...",""],
["mtp_overview.htm","Performance Metrics Overview","Performance Metrics Overview The performance metrics are values that SAM calculates from the hourly performance model results and, for some variab...",""],
["mtp_pump_power.htm","Pump Power","Pump Power For geothermal power systems, SAM reports the pump power, which is equal to the pump work value on the Plant and Equipment page. ",""],
["mt_capacity_factor.htm","Capacity Factor","Capacity Factor The capacity factor is the ratio of the system&#39;s predicted electrical output in the first year of operation to the nameplate outpu...",""],
["mt_gross_to_net_conv_factor.htm","Gross to Net Conv Factor","Gross to Net Conv Factor For CSP systems, SAM displays the ratio of the system&#39;s annual AC electric output to the power block&#39;s gross electric out...",""],
["mt_heat_rate.htm","Heat Rate and Thermal Efficiency","Heat Rate and Thermal Efficiency For biomass power systems, SAM reports the heat rate and thermal efficiency values from the system&#39;s net annual e...",""],
["mt_kwhkwyear1.htm","First year kWhac/kWdc","First year kWhac/kWdc For PV systems, SAM reports the ratio of the system&#39;s annual AC electric output in Year one to it&#39;s nameplate DC capacity: F...",""],
["mt_plant_capacity.htm","Plant Capacity","Plant Capacity For geothermal co-production systems, SAM reports the plant&#39;s capacity, which is equal to the resource power potential value on the...",""],
["mt_resource_capability.htm","Resource Capability","Resource Capability For geothermal co-production systems, SAM reports the plant&#39;s resource capability, which is equal to the resource power potent...",""],
["mt_solar_fraction.htm","Solar Fraction","Solar Fraction For solar water heating systems, the solar fraction is the ratio of solar energy to total energy delivered to the water storage tan...",""],
["mt_system_performance_factor.htm","System Performance Factor","System Performance Factor The system performance factor is a measure of a photovoltaic system&#39;s annual electric generation output in AC kWh compar...",""],
["multiple_systems.htm","Multiple Subsystems","Multiple Subsystems A multiple subsystems analysis allows you to model a power system as a combination of subsystems. This makes it possible to mo...",""],
["notes.htm","Notes","Notes The Notes feature allows you to store text associated with each input page and with the Results page. To create notes: 1. From any input pag...",""],
["p50p90.htm","P50/P90 Analysis","P50/P90 Analysis A P90 value is a value that is expected to be met or exceeded 90% of the time. SAM can generate P50 and P90 values for a system&#39;s...",""],
["parabolic_trough_empirical.htm","Parabolic Trough Empirical","Parabolic Trough Empirical The empirical trough model models the same type of parabolic trough system as the physical trough model, but uses a set...",""],
["parabolic_trough_physical.htm","Parabolic Trough Physical","Parabolic Trough Physical The physical trough model calculates the electricity delivered to the grid by a parabolic trough solar field that delive...",""],
["parametric.htm","Parametric Analysis","Parametric Analysis A parametric analysis makes it possible to create graphs showing the relationship between a result metric and one or more inpu...",""],
["performance_metrics.htm","Performance Metrics","Performance Metrics SAM displays performance metrics on the Results page after running simulations. For a general description of the Metrics table...",""],
["photovoltaic_systems.htm","Photovoltaic Systems","Photovoltaic Systems A photovoltaic system converts light from the sun into electricity. SAM models grid-connected photovoltaic systems that consi...",""],
["pm_dish_stirling.htm","Dish Stirling","Dish Stirling After running simulations, SAM displays time series results for the dish stirling model on the Results page Tables and Time Series g...",""],
["pm_empirical_trough.htm","Parabolic Trough (Empirical)","Parabolic Trough (Empirical) After running simulations, SAM displays time series results for the empirical trough model on the Results page Tables...",""],
["pm_flat_plate_pv.htm","Flat Plate PV","Flat Plate PV After running simulations, SAM displays time series results for the flat plate model on the Results page Tables and Time Series grap...",""],
["pm_generic_solar.htm","Generic Solar System","Generic Solar System After running simulations, SAM displays time series results for the generic solar system model on the Results page Tables and...",""],
["pm_geothermal.htm","Geothermal","Geothermal After running simulations, SAM displays time series results for the Geothermal performance model on the Results page Tables and Time Se...",""],
["pm_high-x_concentrating_pv.htm","High-X Concentrating PV","High-X Concentrating PV After running simulations, SAM displays time series results for the high-X concentrating PV (HCPV) model on the Results pa...",""],
["pm_linear_fresnel.htm","Linear Fresnel","Linear Fresnel After running simulations, SAM displays time series results for the linear fresnel model on the Results page Tables and Time Series...",""],
["pm_outputs.htm","Performance Model Results","Performance Model Results The performance model outputs are hourly (or sub-hourly) simulation results from the SAM performance models. The perform...",""],
["pm_overview.htm","Performance Results Overview","Performance Results Overview The performance model results are hour-by-hour values calculated during simulations. After running simulations, SAM d...",""],
["pm_physical_trough.htm","Parabolic Trough (Physical)","Parabolic Trough (Physical) After running simulations, SAM displays time series results for the physical trough model on the Results page Tables a...",""],
["pm_power_tower_ds.htm","Power Tower (Direct Steam)","Power Tower (Direct Steam) After running simulations, SAM displays time series results for the direct steam power tower model on the Results page ...",""],
["pm_power_tower_ms.htm","Power Tower (Molten Salt)","Power Tower (Molten Salt) After running simulations, SAM displays time series results for the molten salt power tower model on the Results page Ta...",""],
["pm_pvwatts.htm","PVWatts","PVWatts After running simulations, SAM displays performance output data for the PVWatts model on the Results page Tables and Time Series graphs. N...",""],
["pm_solar_water_heating.htm","Solar Water Heating","Solar Water Heating Model Hourly Data After running simulations, SAM displays hourly results for the solar water heating model on the Results page...",""],
["power_tower_direct_steam.htm","Power Tower Direct Steam","Power Tower Direct Steam The direct steam power tower consists of the same components and functionality of the molten salt power tower, with two i...",""],
["power_tower_molten_salt.htm","Power Tower Molten Salt","Power Tower Molten Salt A power tower system (also called a central receiver system) is a type of concentrating solar power (CSP) system that cons...",""],
["publishing_checklist.htm","PUBLISHING CHECKLIST","PUBLISHING CHECKLIST 1. Update contextmap.txt 2. Change SAM Version number 3. Compile help 4. Replace zoom_search.js file 5. Test 6. For official ...",""],
["pvfp_array.htm","Array","Array The Flat Plate PV model&#39;s Array page displays variables and options that specify the number of modules and inverters in the system, AC derat...",""],
["pvfp_flat_plate_pv.htm","Flat Plate PV","Flat Plate PV The Flat Plate PV option represents the performance of a photovoltaic system using separate models to represent the performance of t...",""],
["pvfp_inverter.htm","Inverter ","Inverter The Inverter page allows you to choose an inverter performance model and either choose an inverter from a list, or enter inverter paramet...",""],
["pvfp_module.htm","Module","Module The Module page allows you to choose a photovoltaic module performance model and either choose a module from a list, specify module paramet...",""],
["pvfp_sizing_the_pv_system.htm","Sizing the Flat Plate PV System","Sizing the Flat Plate PV System For photovoltaic systems, SAM considers the system nameplate capacity to be the photovoltaic array&#39;s nameplate cap...",""],
["pvfp_subarrays.htm","PV Subarrays","PV Subarrays The Flat Plate PV Subarrays page allows you to specify the number of strings, tracking and orientation, shading and soiling, and DC d...",""],
["pvhcpv_high-x_concentrating_pv_hcpv.htm","High-X Concentrating PV (HCPV)","High-X Concentrating PV (HCPV) The High-X Concentrating PV (HCPV) represents a HCPV system as an array of modules with one or more inverters as sp...",""],
["pvwatts.htm","PVWatts","PVWatts The PVWatts Solar Array page displays variables for SAM&#39;s implementation of NREL&#39;s PVWatts model. SAM includes an implementation of NREL&#39;s...",""],
["pvwatts_solar_array.htm","PVWatts Solar Array","PVWatts Solar Array The PVWatts Solar Array page displays variables for SAM&#39;s implementation of NREL&#39;s PVWatts model. For links to references desc...",""],
["pv_getting_started.htm","Getting Started with PV","Getting Started with PV The procedure below describes the basic steps to get started modeling a project based on photovoltaic technology. For gene...",""],
["pv_microinverters.htm","Microinverters","Microinverters For an example of how to model a PV system with microinverters, see the sample file PV Microinverters.zsam (on the File menu, click...",""],
["pv_shading.htm","Shading","Shading SAM models two types of shading for photovoltaic systems: Array shading affects the entire subarray (Flat Plate PV) or array (PVWatts) uni...",""],
["pv_system_costs.htm","PV System Costs","PV System Costs The PV System Costs page provides access to variables that define the installation and operating costs of a photovoltaic project. ...",""],
["references.htm","References","References Parabolic Trough Technology and Modeling Burkholder F et al, 2009. Heat Loss Testing of Schott&#39;s 2008 PTR70 Parabolic Trough Receiver. ...",""],
["reports.htm","Reports","Reports A report is a PDF document with text, tables, and graphs describing your analysis. A report draws data from inputs and results. Generate R...",""],
["resource_and_power_generation.htm","Geothermal Co-Pro Resource and Power Generation","Resource and Power Generation The Geothermal Co-Production model estimates power output from co-production resources based on the resource tempera...",""],
["results.htm","Results","Results SAM displays tables and graphs of results from the performance and financial models on the Results page. For a general description of the ...",""],
["results_page.htm","Results Page","Results Page The Results page displays data from both the performance model and financial model. You can export data from any graph or table displ...",""],
["retail_electric_rates.htm","Retail Electricity Rates","Retail Electricity Rates The retail electricity rates input pages are available when you choose either the Residential or Commercial financing opt...",""],
["run_simulations.htm","Run Simulations","Run Simulations After reviewing and modifying inputs on the input pages, click the Run all Simulations button to run simulations: SAM runs simulat...",""],
["samul.htm","SamUL Scripting Language","SamUL Scripting Language SamUL is a scripting language that you can use to automate simulation runs in SAM. For a more detailed reference informat...",""],
["samul_arrays_of_data.htm","SamUL: Arrays of Data","Arrays of Data Often you need to store a list of related values. For example, you may need to refer to the price of energy in different years. Or ...",""],
["samul_code_sample.htm","Code Sample: Latin Hypercube Sampling","Code Sample: Latin Hypercube Sampling SamUL&#39;s Latin Hypercube Sampling (LHS) functions are useful for statistical and uncertainty analyses. The LH...",""],
["samul_data_variables.htm","SamUL: Data Variables","Data Variables General Syntax In SamUL, a program statement is generally placed on a line by itself, and the end-of-line marks the end of the stat...",""],
["samul_flow_control.htm","SamUL: Flow Control","Flow Control Comparison Operators SamUL supports many ways of comparing data. These types of tests can control the program flow with branching and...",""],
["samul_function_calls.htm","SamUL: Function Calls","Function Calls It is usually good programming practice to split a larger program up into smaller sections, often called procedures, functions, or ...",""],
["samul_input_output.htm","SamUL: Input, Output, and System Access","Input, Output, and System Access SamUL provides a variety of standard library functions to work with files, directories, and interact with other p...",""],
["samul_interfacing_with_sam.htm","SamUL: Interfacing with SAM Analyses","Interfacing with SAM Analyses The SamUL language would be of little interest if it did not allow for direct manipulation and automation of SAM ana...",""],
["samul_library_reference.htm","SamUL: Library Reference","Library Reference Type/Data Manipulation TypeOf ( ):STRING Returns a description of the argument type. Integer ( VARIANT ):INTEGER Converts the va...",""],
["samul_overview.htm","Why use SamUL?","Why use SamUL? The SAM User Language (SamUL) is a built-in scripting language that allows a user to automate tasks and perform more complex analys...",""],
["samul_write_a_simple_script.htm","Writing and Running SamUL Scripts","Writing and Running SamUL Scripts A SamUL script is code that you write in a SAM file. SAM stores the script in the file along with cases represen...",""],
["sdk.htm","Software Development Kit (SDK)","Software Development Kit (SDK) The SAM Simulation Core (SSC) software development kit is a collection of developer tools for creating renewable en...",""],
["sensitivity_analysis.htm","Sensitivity Analysis","Sensitivity Analysis The sensitivity analysis option allows you to specify a range of values as a percentage for one or more input variables to in...",""],
["shw_overview.htm","Solar Water Heating Overview","Solar Water Heating Overview The solar water heating (SWH) model represents a one-tank water or glycol system with an auxiliary electric heater. T...",""],
["shw_system.htm","Solar Water Heating","Solar Water Heating The SWH System page is where you specify the design parameters for the solar water heating system. For a general description o...",""],
["simulation_options.htm","Analysis Options","Analysis Options Analysis Options allow you to set up analyses that involve multiple simulations: Parametric Analysis : Assign multiple values to ...",""],
["simulator_options.htm","Simulator Options","Simulator Options The Simulator Options are for advanced analyses that involve either changing the simulation time step, or working with custom TR...",""],
["snip_htf_properties.htm","HTF Properties","HTF Properties Heat transfer fluids on the Field HTF Fluid list. Name Type Min Optimal Operating Temp ºC Max Optimal Operating Temp* ºC Freeze Poi...",""],
["snip_pm_csp_note.htm","Performance Model CSP Note","Performance Model CSP Note Notes. The solar radiation values (DNI) represent total energy values over the time step, and are equivalent to the val...",""],
["snip_pvcec-sandia-tempcorr.htm","PV CEC Sandia Temperature Correction","PV CEC Sandia Temperature Correction ",""],
["solar_hot_water.htm","Solar Water Heating","Solar Water Heating The Solar Hot Water model represents a two-tank glycol system with an auxiliary electric heater and storage tank for residenti...",""],
["start_project.htm","Start a Project","Start a Project The following procedure describes the basic steps to set up and run a simulation of a project. See also: Financing Overview Techno...",""],
["statistical.htm","Statistical","Statistical A statistical analysis allows you to examine the effect of uncertainty in the value of one or more input variables on an output metric...",""],
["swh_system_costs.htm","SWH System Costs","SWH System Costs To view the SWH System Costs page, click SWH System Costs on the main window&#39;s navigation menu. Note that for the solar water hea...",""],
["system_costs.htm","System Costs","System Costs The System Costs page allows you to specify project installation costs, and operation and maintenance (O&#38;M) costs. For a general desc...",""],
["system_costs_overview.htm","System Costs Overview","System Costs Overview When you run SAM, you provide information about the cost of installing and operating the system by specifying inputs on the ...",""],
["tabular_data_browser.htm","Tables","Tables The Tables on the Results page display results from the performance and financial models from the base case simulation, which reflects data...",""],
["td_ppa.htm","PPA Revenue with TOD Factors","PPA Revenue with TOD Factors This topic describes the time-of-delivery (TOD) variables available on the Results page after you run simulations for...",""],
["td_retail.htm","Retail Electricity Savings","Retail Electricity Savings For projects with the residential or commercial financing option (not including commercial PPA) that buy and sell elect...",""],
["td_variables_overview.htm","TD_Overview","Time Dependent Pricing Overview SAM can model PPA price time-of-delivery (TOD) factors or retail time-of-use (TOU) rates. For a description of sim...",""],
["technology_options.htm","Performance Models","Performance Models Each energy technology in SAM has a corresponding performance model that performs calculations specific to the technology. Most...",""],
["time_dependent_pricing.htm","Savings and Revenue","Savings and Revenue SAM reports Revenue results for PPA projects (utility financing options), and Savings results for retail projects (residential...",""],
["towerds_heliostat_field.htm","Heliostat Field","Heliostat Field The Heliostat Field page displays the variables that specify the position of the heliostats in the solar field along with the heli...",""],
["towerds_overview.htm","Tower Direct Steam Overview","Tower Direct Steam Overview The direct steam power tower is based upon the same concepts as the molten salt power tower: a first-principles energy...",""],
["towerds_parasitics.htm","Parasitics","Parasitics The parameters on the Parasitics page describe parasitic electrical loads and other losses in the power tower system. Page numbers rele...",""],
["towerds_power_cycle.htm","Power Cycle","Power Cycle The steam flowing through the tower is both the heat transfer fluid that transfers energy from the receiver and the working fluid of t...",""],
["towerds_tower_and_receiver.htm","Tower and Receiver","Tower and Receiver The Tower and Receiver page displays variables that specify the geometry of the heat collection system. The receiver model uses...",""],
["towerms_heliostat_field.htm","Tower Heliostat Field","Heliostat Field To view the Heliostat page, click Heliostat Field on the main window&#39;s navigation menu. Note that for the power tower input pages ...",""],
["towerms_overview.htm","Tower Molten Salt Overview","Tower Molten Salt Overview A power tower system (also called a central receiver system) is a type of concentrating solar power (CSP) system that c...",""],
["towerms_parasitics.htm","Tower Parasitics","Parasitics To view the Parasitics page, click Parasitics on the main window&#39;s navigation menu. Note that for the power tower input pages to be ava...",""],
["towerms_power_cycle.htm","Tower Power Cycle","Power Cycle To view the Power Cycle page, click Power Cycle on the main window&#39;s navigation menu. Note that for the power tower input pages to be ...",""],
["towerms_thermal_storage.htm","Tower Thermal Storage","Thermal Storage To view the Thermal Storage page, click Thermal Storage on the main window&#39;s navigation menu. Note that for the power tower input ...",""],
["towerms_tower_and_receiver.htm","Tower and Receiver","Tower and Receiver To view the Tower and Receiver page, click Tower and Receiver on the main window&#39;s navigation menu. Note that for the power tow...",""],
["tower_system_costs.htm","Tower System Costs","Tower System Costs To view the Tower System Costs page, click Tower System Costs on the main window&#39;s navigation menu. Note that for the power tow...",""],
["troughempirical_overview.htm","Trough Empirical Overview","Trough Empirical Overview A parabolic trough system is a type of concentrating solar power (CSP) system that collects direct normal solar radiatio...",""],
["troughempirical_parasitics.htm","Empirical Trough Parasitics","Parasitics To view the Parasitics page, click Parasitics on the main window&#39;s navigation menu. Note that for the empirical trough input pages to b...",""],
["troughempirical_power_block.htm","Empirical Trough Power Block","Power Block To view the Power Block page, click Power Block on the main window&#39;s navigation menu. Note that for the empirical trough input pages t...",""],
["troughempirical_sca_hce.htm","Empirical Trough SCA / HCE","SCA / HCE To view the SCA / HCE page, click Solar Field on the main window&#39;s navigation menu. Note that for the empirical trough input pages to be...",""],
["troughempirical_solar_field.htm","Empirical Trough Solar Field","Solar Field To view the Solar Field page, click Solar Field on the main window&#39;s navigation menu. Note that for the empirical trough input pages t...",""],
["troughempirical_thermal_storage.htm","Empirical Trough Thermal Storage","Thermal Storage To view the Thermal Storage page, click Thermal Storage on the main window&#39;s navigation menu. Note that for the empirical trough i...",""],
["troughphysical_collectors_scas.htm","Physical Trough Collectors (SCAs)","Collectors (SCAs) To view the Collectors page, click Collectors (SCAs) on the main window&#39;s navigation menu. Note that for the physical trough inp...",""],
["troughphysical_overview.htm","Trough Physical Overview","Trough Physical Overview A parabolic trough system is a type of concentrating solar power (CSP) system that collects direct normal solar radiation...",""],
["troughphysical_parasitics.htm","Physical Trough Parasitics","Parasitics To view the Parasitics page, click Parasitics on the main window&#39;s navigation menu. Note that for the physical trough input pages to be...",""],
["troughphysical_power_cycle.htm","Physical Trough Power Cycle","Power Cycle To view the Power Cycle page, click Power Cycle on the main window&#39;s navigation menu. Note that for the physical trough input pages to...",""],
["troughphysical_receivers_hces.htm","Physical Trough Receivers (HCEs)","Receivers (HCEs) To view the Receivers page, click Receivers (HCEs) on the main window&#39;s navigation menu. Note that for the physical trough input ...",""],
["troughphysical_solar_field.htm","Physical Trough Solar Field","Solar Field To view the Solar Field page, click Solar Field on the main window&#39;s navigation menu. Note that for the physical trough input pages to...",""],
["troughphysical_thermal_storage.htm","Physical Trough Thermal Storage","Thermal Storage To view the Thermal Storage page, click Thermal Storage on the main window&#39;s navigation menu. Note that for the physical trough in...",""],
["trough_system_costs.htm","Trough System Costs","Trough System Costs To view the Trough System Costs page, click Trough System Costs on the main window&#39;s navigation menu. Note that for the empiri...",""],
["user_support.htm","User Support","User Support For information about any page in the software, do one of the following: Press the F1 key in Windows or Command-? in Mac OS. Click th...",""],
["user_variables.htm","Exchange Variables","Exchange Variables The Exchange Variables page displays two types of special variables. SAM only uses these variables under special conditions -- ...",""],
["utility_rate.htm","Retail Utility Rate","Utility Rate To view the Utility Rate page, open a case with either the residential or commercial financing option, and then click Utility Rate in...",""],
["utility_rates_overview.htm","Rates Overview","Rates Overview For projects with residential and commercial financing, you specify electricity prices on the Utility Rate page and an electric loa...",""],
["weather_create_tmy3.htm","Create TMY3 File","Create TMY3 File SAM&#39;s TMY3 creator is a tool for converting your own weather data into the TMY3 format. Although it is possible to create your ow...",""],
["weather_data.htm","Weather Data","Weather Data Each of the performance models in SAM requires data describing the renewable resource and ambient weather conditions at the project l...",""],
["weather_embed.htm","Embed a Weather File","Embed a Weather File When you want to share a SAM project with another person, and the project uses one or more weather files that the other perso...",""],
["weather_format.htm","Weather File Formats","Weather File Formats A SAM weather file is a text file that contains hourly data describing the solar resource, wind speed, temperature, and other...",""],
["weather_location_lookup.htm","Download Weather File","Download Weather File SAM&#39;s Download Weather File feature allows you to type an address, zip code, or latitude and longitude to download a weather...",""],
["weather_manage_folders.htm","Weather File Folders","Weather File Folders When you install SAM, it creates a default weather file folder in the SAM installation folder (C:\\SAM\\SAM 2014.1.14\\weather b...",""],
["weather_overview.htm","Weather Data Overview","Weather Data Overview SAM&#39;s performance models use data from a weather file to simulate a system&#39;s hourly performance for a single year. Each perf...",""],
["weather_viewer.htm","Weather Data Viewer","Weather Data Viewer SAM displays summary data from a weather file. If you want to see the weather data itself, you can use the weather data viewer...",""],
["weather_web.htm","Weather Data Online","Weather Data Online SAM allows you to use correctly formatted weather files that you download from the web. Weather files must meet the following ...",""],
["welcome_page.htm","Welcome Page","Welcome Page When you start SAM, it displays a Welcome window with several options for starting a project: Create a new file to start a project. T...",""],
["window_case_compare.htm","Case Compare","Case Compare Case Compare is a flexible viewer and editor that allows you to explore the data in your SAM files. It allows you to build a table of...",""],
["window_edit_graph.htm","Edit Graph","Edit / Add New Graph The Edit Graph and Add New Graph windows allow you to specify the properties of a graph. As you change properties, SAM automa...",""],
["window_geothermal_lookup.htm","Geothermal Resource Lookup","Geothermal Resource Lookup The Geothermal Resource Lookup window allows you to download depth and temperature data for locations in the United Sta...",""],
["window_numeric_ranges.htm","Numeric Ranges","Numeric Ranges The numeric ranges window allows you to assign one or more values to a parametric variable. Note. SAM runs a complete hourly simula...",""],
["window_optimization_wizard.htm","Optimization Wizard","Optimization Wizard The power tower optimization wizard simplifies the task of choosing values for the relatively large number of input parameters...",""],
["window_specify_missing_wind_data.htm","Specify Missing Wind Data","Specify Missing Wind Data When you use the Download Weather File feature to download wind resource data for a location east of about longitude 100...",""],
["window_technology_market.htm","Technology and Market","Technology and Market The Technology and Market window allows you to choose options for a new case or modify options for the current case. Select ...",""],
["window_tmy3_creator.htm","TMY3 Creator","TMY3 Creator The TMY3 Creator allows you to cut and paste your own weather data from columns in a spreadsheet program into SAM, and to save it as ...",""],
["window_weather_data_settings.htm","Weather Data Settings","Weather Data Settings The Weather Data Settings window allows you to choose weather file folders where SAM looks for weather files, and where it s...",""],
["wind_farm.htm","Wind Farm","Wind Farm The Wind Farm page allows you to specify the number of turbines in the project and includes a simple representation of the wind farm lay...",""],
["wind_overview.htm","Wind Power Overview","Wind Power Overview The Wind Power model is for projects involving one or more large or small turbines with any of the financial models for reside...",""],
["wind_power.htm","Wind Power","Wind Power The Wind Power model is for projects involving one or more large or small turbines with any of the financing options . The wind power m...",""],
["wind_resource.htm","Wind Resource","Wind Resource The Wind Resource page allows you to choose weather data to use for your simulation with the Wind Power model. Wind Resource by Loca...",""],
["wind_siting.htm","Siting Considerations","Siting Considerations The Siting Considerations page allows you to download a list of public agencies and land ownership and environmental informa...",""],
["wind_system_costs.htm","Wind System Costs","Wind System Costs The Wind System Costs page allows you to specify the costs of a wind power project. Note. The default cost values that appear wh...",""],
["wind_turbine.htm","Turbine","Turbine The wind turbine parameters specify the turbine power curve and hub height of a single turbine. For a project with multiple turbines, SAM ...",""],
["youtube_channel.htm","YouTube Channel","YouTube Channel For video demonstrations of SAM, please visit the SAM Demo Video YouTube Channel at: http://www.youtube.com/user/SAMDemoVideos Dem...",""]];
