hmLoadTopic({
hmKeywords:"",
hmTitle:"Rotate objects",
hmDescription:"You can rotate rectangular objects in the horizontal plane. In bird\'s eye view, drag the rotation handle, or in any view change the rotation property.",
hmPrevLink:"3dshad-resize.html",
hmNextLink:"3dshad-delete.html",
hmParentLink:"3dshad-how-to.html",
hmBreadCrumbs:"<a href=\"3d_shade_calculator.html\">3D Shade Calculator<\/a> &gt; <a href=\"3dshad-how-to.html\">How-To<\/a>",
hmTitlePath:"3D Shade Calculator > How-To > Rotate objects",
hmHeader:"<h1 class=\"p_Heading1\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_Heading1\">Rotate objects<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Text\"><span class=\"f_Text\">You can rotate rectangular objects in the horizontal plane. In bird\'s eye view, drag the rotation handle, or in any view change the rotation property.<\/span><\/p>\n\r<p class=\"p_Text\"><span class=\"f_Text\">For active surfaces, the rotation angle is its azimuth angle, with 180 degrees defined as the rotation with the surface\'s width parallel to the X axis.<\/span><\/p>\n\r<p class=\"p_TitleProcedure\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_TitleProcedure\">To rotate an object with your mouse.<\/span><\/p>\n\r<p class=\"p_ProcedureStep\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 1.5000rem;\"><span class=\"f_ProcedureStep\" style=\"display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">1.<\/span><span class=\"f_ProcedureStep\">Click <\/span><span class=\"f_CHInterfaceElement\">Bird\'s eye<\/span><span class=\"f_ProcedureStep\">.<\/span><\/p>\n\r<p class=\"p_ProcedureStep\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 1.5000rem;\"><span class=\"f_ProcedureStep\" style=\"display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">2.<\/span><span class=\"f_ProcedureStep\">Click the object to select it.<\/span><\/p>\n\r<p class=\"p_ProcedureStepLast\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 1.5000rem;\"><span class=\"f_ProcedureStep\" style=\"display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">3.<\/span><span class=\"f_ProcedureStepLast\">Drag the rotation handle <\/span><img alt=\"ss-icon-rotate\" style=\"margin:0;width:1.4375rem;height:1.4375rem;border:none\" src=\".\/images\/ss-icon-rotate.png\"\/><span class=\"f_ProcedureStepLast\">.<\/span><\/p>\n\r<p class=\"p_TitleProcedure\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_TitleProcedure\">To rotate an object by editing its properties<\/span><\/p>\n\r<p class=\"p_ProcedureStep\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 1.5000rem;\"><span class=\"f_ProcedureStep\" style=\"display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">1.<\/span><span class=\"f_ProcedureStep\">In any view, click the object to select it.<\/span><\/p>\n\r<p class=\"p_ProcedureStepLast\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 1.5000rem;\"><span class=\"f_ProcedureStep\" style=\"display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">2.<\/span><span class=\"f_ProcedureStepLast\">Change the value of the rotation property and press the Tab or Enter key.<\/span><\/p>"
})
