hmLoadTopic({
hmKeywords:"",
hmTitle:"Delete and copy objects",
hmDescription:"You can delete and copy objects from any view. Note. The SAM shade calculator does not have an Undo feature. To delete an object Click the object to select it. Click Delete in",
hmPrevLink:"3dshad-rotate.html",
hmNextLink:"3dshad-colors.html",
hmParentLink:"3dshad-how-to.html",
hmBreadCrumbs:"<a href=\"3d_shade_calculator.html\">3D Shade Calculator<\/a> &gt; <a href=\"3dshad-how-to.html\">How-To<\/a>",
hmTitlePath:"3D Shade Calculator > How-To > Delete and copy objects",
hmHeader:"<h1 class=\"p_Heading1\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_Heading1\">Delete and copy objects<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Text\"><span class=\"f_Text\">You can delete and copy objects from any view.<\/span><\/p>\n\r<p class=\"p_Note\"><span class=\"f_CHNote\">Note.<\/span><span class=\"f_Note\"> The SAM shade calculator does not have an Undo feature.<\/span><\/p>\n\r<p class=\"p_TitleProcedure\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_TitleProcedure\">To delete an object<\/span><\/p>\n\r<p class=\"p_ProcedureStep\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 1.5000rem;\"><span class=\"f_ProcedureStep\" style=\"display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">1.<\/span><span class=\"f_ProcedureStep\">Click the object to select it.<\/span><\/p>\n\r<p class=\"p_ProcedureStep\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 1.5000rem;\"><span class=\"f_ProcedureStep\" style=\"display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">2.<\/span><span class=\"f_ProcedureStep\">Click <\/span><span class=\"f_CHInterfaceElement\">Delete<\/span><span class=\"f_ProcedureStep\"> in the bar above the object\'s property table.<\/span><\/p>\n\r<p class=\"p_TitleProcedure\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_TitleProcedure\">To copy an object<\/span><\/p>\n\r<p class=\"p_ProcedureStep\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 1.5000rem;\"><span class=\"f_ProcedureStep\" style=\"display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">1.<\/span><span class=\"f_ProcedureStep\">Click the object to select it<\/span><\/p>\n\r<p class=\"p_ProcedureStep\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 1.5000rem;\"><span class=\"f_ProcedureStep\" style=\"display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">2.<\/span><span class=\"f_ProcedureStep\">Click <\/span><span class=\"f_CHInterfaceElement\">Duplicate<\/span><span class=\"f_ProcedureStep\"> in the bar above the object\'s property table.<\/span><\/p>\n\r<p class=\"p_ImageCaption\"><span class=\"f_ImageCaption\">Select an Object to Copy or Delete it.<\/span><\/p>\n\r<p class=\"p_ImageCaption\"><img alt=\"ss-copy-delete\" style=\"margin:0 auto 0 auto;width:30.6875rem;height:14.8125rem;border:none\" src=\".\/images\/ss-copy-delete.png\"\/><\/p>\n\r"
})
