hmLoadTopic({
hmKeywords:"",
hmTitle:"Analyze",
hmDescription:"Click Analyze after creating the shading scene to generate shading data. You can then export shading data for use in simulation models and other software. This section is a...",
hmPrevLink:"3dshad-elevations.html",
hmNextLink:"3dshad-import_export.html",
hmParentLink:"3dshad-reference.html",
hmBreadCrumbs:"<a href=\"3d_shade_calculator.html\">3D Shade Calculator<\/a> &gt; <a href=\"3dshad-reference.html\">Reference<\/a>",
hmTitlePath:"3D Shade Calculator > Reference > Analyze",
hmHeader:"<h1 class=\"p_Heading1\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_Heading1\">Analyze<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Text\"><span class=\"f_Text\">Click <\/span><span class=\"f_CHInterfaceElement\">Analyze<\/span><span class=\"f_Text\"> after creating the shading scene to generate shading data. You can then export shading data for use in simulation models and other software. This section is a quick reference for the Analyze options. For more details see:<\/span><\/p>\n\r<p class=\"p_List\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 1.5000rem;\"><span class=\"f_List\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_List\"><a href=\"3dshad-generate-data.html\" class=\"topiclink\">Generate shade data<\/a><\/span><\/p>\n\r<p class=\"p_ListLast\" style=\"text-indent: 0; page-break-inside: avoid; padding-left: 1.5000rem; margin-left: 1.5000rem;\"><span class=\"f_List\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_ListLast\"><a href=\"3dshad-export.html\" class=\"topiclink\">Export shade data<\/a><\/span><\/p>\n\r<p class=\"p_Note\"><span class=\"f_CHNote\">Note.<\/span><span class=\"f_Note\"> To generate SAM shading inputs, click <a href=\"3dshad-save-close.html\" class=\"topiclink\">Save and Close<\/a>. You do not need to click <\/span><span class=\"f_CHInterfaceElement\">Analyze<\/span><span class=\"f_Note\"> to generate shading data for SAM.<\/span><\/p>\n\r<p class=\"p_VariableName\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_VariableName\">Diurnal analysis<\/span><\/p>\n\r<p class=\"p_VariableDescription\"><span class=\"f_VariableDescription\">Click this button to a generate table of hour-by-month beam shade loss percentages.<\/span><\/p>\n\r<p class=\"p_VariableDescription\"><span class=\"f_VariableDescription\">When your scene contains more than one active surface, you can generate a separate hour-by-month table for the surfaces by assigning group names to the surfaces. See <a href=\"3dshad-generate-data.html\" class=\"topiclink\">Generate shading data for details<\/a>.<\/span><\/p>\n\r<p class=\"p_VariableName\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_VariableName\">Time series analysis<\/span><\/p>\n\r<p class=\"p_VariableDescription\"><span class=\"f_VariableDescription\">Generate a CSV file of beam shade loss percentages for each of the time steps in a year.<\/span><\/p>\n\r<p class=\"p_VariableName\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_VariableName\">Diffuse analysis<\/span><\/p>\n\r<p class=\"p_VariableDescription\"><span class=\"f_VariableDescription\">Generate a sky diffuse loss percentage.<\/span><\/p>\n\r"
})
