hmLoadTopic({
hmKeywords:"",
hmTitle:"Create a Project",
hmDescription:"A SAM project consists of one or more cases. Each case stores inputs and results for a renewable energy system. When you save a project, SAM creates a project file with the...",
hmPrevLink:"welcome_page.html",
hmNextLink:"choose_models.html",
hmParentLink:"getting_started.html",
hmBreadCrumbs:"<a href=\"getting_started.html\">Getting Started<\/a>",
hmTitlePath:"Getting Started > Create a Project",
hmHeader:"<h1 class=\"p_Heading1\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_Heading1\">Create a Project<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Text\"><span class=\"f_Text\">A SAM project consists of one or more <a href=\"manage_cases.html\" class=\"topiclink\">cases<\/a>. Each case stores inputs and results for a renewable energy system. When you save a project, SAM creates a project file with the <\/span><span class=\"f_CHFileName\">.sam<\/span><span class=\"f_Text\"> extension.<\/span><\/p>\n\r<p class=\"p_TitleProcedure\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_TitleProcedure\">To create a SAM project:<\/span><\/p>\n\r<p class=\"p_ProcedureStep\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 1.5000rem;\"><span class=\"f_ProcedureStep\" style=\"display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">1.<\/span><span class=\"f_ProcedureStep\">On the <a href=\"welcome_page.html\" class=\"topiclink\">Welcome page<\/a>, click <\/span><span class=\"f_CHInterfaceElement\">Start a new project<\/span><span class=\"f_ProcedureStep\"> to create a new project, or on the <a href=\"file_menu.html\" class=\"topiclink\">File menu<\/a>, click <\/span><span class=\"f_CHInterfaceElement\">New project<\/span><span class=\"f_ProcedureStep\">.<\/span><\/p>\n\r<p class=\"p_ProcedureStep\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 1.5000rem;\"><span class=\"f_ProcedureStep\" style=\"display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">2.<\/span><span class=\"f_ProcedureStep\"><a href=\"choose_models.html\" class=\"topiclink\">Choose models<\/a> for your project.<\/span><\/p>\n\r<p class=\"p_ProcedureStepNoNumber\"><span class=\"f_ProcedureStepNoNumber\">SAM creates the project with a single case with all input variables populated with default values.<\/span><\/p>\n\r<p class=\"p_ProcedureStep\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 1.5000rem;\"><span class=\"f_ProcedureStep\" style=\"display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">3.<\/span><span class=\"f_ProcedureStepNoNumber\">On the File menu, click <\/span><span class=\"f_CHInterfaceElement\">Save<\/span><span class=\"f_ProcedureStepNoNumber\"> to save the project as a <\/span><span class=\"f_CHFileName\">.sam<\/span><span class=\"f_ProcedureStepNoNumber\"> file.<\/span><\/p>\n\r<p class=\"p_ProcedureStepNoNumber\"><img alt=\"SS_start-button\" style=\"margin:0;width:16.5000rem;height:22.3125rem;border:none\" src=\".\/images\/ss_start-button.png\"\/><\/p>\n\r"
})
