hmLoadTopic({
hmKeywords:"",
hmTitle:"Pumped Thermal Energy Storage)",
hmDescription:"SAM\'s Pumped Thermal Energy Storage (PTES) model is for a system that stores electricity from the grid in both hot and cold reservoirs, using two-tank Thermal Energy Storage...",
hmPrevLink:"etes_system_control.html",
hmNextLink:"ptes_location_and_resource.html",
hmParentLink:"index.html",
hmBreadCrumbs:"",
hmTitlePath:"Pumped Thermal Energy Storage",
hmHeader:"<h1 class=\"p_Heading1\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_Heading1\">Pumped Thermal Energy Storage)<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Text\"><span class=\"f_Text\">SAM\'s Pumped Thermal Energy Storage (PTES) model is for a system that stores electricity from the grid in both hot and cold reservoirs, using two-tank Thermal Energy Storage (TES) systems for each reservoir. A heat pump converts electricity from the grid to charge the hot tank of the hot reservoir and cold tank of the cold reservoir. A power cycle converts heat from the TES to electricity to deliver to the grid. The dispatch model charges and discharges the TES in response to electricity prices to charge from the grid when prices are low and discharge to the grid when prices are high.<\/span><\/p>\n\r<p class=\"p_Text\"><span class=\"f_Text\">The dispatch model uses a mixed-integer linear program to optimize plant operations to maximize gross profit over a look-ahead period. The model sends the optimized operations solution to a detailed performance model of the plant that ensures accurate component performance and feasible plant behavior. The dispatch model is conceptually similar to the molten salt power tower and electric thermal energy storage dispatch &nbsp;models and shares common routines with them.<\/span><\/p>\n\r<p class=\"p_Text\"><span class=\"f_Text\">For a detailed description of the PTES model see:<\/span><\/p>\n\r<p class=\"p_ListLast\" style=\"text-indent: 0; page-break-inside: avoid; padding-left: 1.5000rem; margin-left: 1.5000rem;\"><span class=\"f_ListLast\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_ListLast\">Neises, T.; Hamilton, B.; Martinek, J.; McTigue, J. (2022) Stand-alone and Hybrid Electric Thermal Energy Storage in the System Advisor Model. 51 pp. NREL\/TP-5700-82989. (<a href=\"https:\/\/www.nrel.gov\/docs\/fy22osti\/82989.pdf\" class=\"weblink\">PDF 2.3 MB<\/a>)<\/span><\/p>\n\r<p class=\"p_Text\"><span class=\"f_Text\">&nbsp;<\/span><\/p>\n\r"
})
