hmLoadTopic({
hmKeywords:"",
hmTitle:"Hybrid Systems",
hmDescription:"SAM\'s hybrid system models combine two or more power generation subsystems with battery storage. SAM runs a simulation for each subsystem, and adds the subsystem generation...",
hmPrevLink:"battery_results.html",
hmNextLink:"hybrid_system.html",
hmParentLink:"index.html",
hmBreadCrumbs:"",
hmTitlePath:"Hybrid Systems",
hmHeader:"<h1 class=\"p_Heading1\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_Heading1\">Hybrid Systems<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Text\"><span class=\"f_Text\">SAM\'s hybrid system models combine two or more power generation subsystems with battery storage. SAM runs a simulation for each subsystem, and adds the subsystem generation profiles together to calculate hybrid system\'s generation profile. It then dispatches the battery based on the hybrid generation profile.<\/span><\/p>\n\r<p class=\"p_Text\"><span class=\"f_Text\">The available hybrid system configurations are:<\/span><\/p>\n\r<p class=\"p_List\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 1.5000rem;\"><span class=\"f_List\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_List\">PVWatts Wind Battery<\/span><\/p>\n\r<p class=\"p_List\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 1.5000rem;\"><span class=\"f_List\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_List\">PVWatts Wind Fuel Cell Battery<\/span><\/p>\n\r<p class=\"p_List\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 1.5000rem;\"><span class=\"f_List\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_List\">Photovoltaic Wind Battery <\/span><\/p>\n\r<p class=\"p_ListLast\" style=\"text-indent: 0; page-break-inside: avoid; padding-left: 1.5000rem; margin-left: 1.5000rem;\"><span class=\"f_List\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_ListLast\">Custom Generation PVWatts Wind Fuel Cell Battery<\/span><\/p>"
})
