hmLoadTopic({
hmKeywords:"",
hmTitle:"Losses",
hmDescription:"The Losses tab on the Results page displays a Sankey diagram showing the energy at different points in the system, and the source of energy losses at each point.",
hmPrevLink:"summary.html",
hmNextLink:"graphs.html",
hmParentLink:"results.html",
hmBreadCrumbs:"<a href=\"results.html\">Results<\/a>",
hmTitlePath:"Results > Losses",
hmHeader:"<h1 class=\"p_Heading1\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_Heading1\">Losses<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Text\"><span class=\"f_Text\">The <\/span><span class=\"f_CHInterfaceElement\">Losses<\/span><span class=\"f_Text\"> tab on the Results page displays a Sankey diagram showing the energy at different points in the system, and the source of energy losses at each point.<\/span><\/p>\n\r<p class=\"p_TitleProcedure\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_TitleProcedure\">To view the loss diagram:<\/span><\/p>\n\r<p class=\"p_ProcedureStep\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 1.5000rem;\"><span class=\"f_ProcedureStep\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_ProcedureStep\">On the Results page, click the <\/span><span class=\"f_CHInterfaceElement\">Losses<\/span><span class=\"f_ProcedureStep\"> tab.<\/span><\/p>\n\r<p class=\"p_ProcedureStepNoNumber\"><img alt=\"SS_Results-ButtonsLossDiagram\" style=\"margin:0;width:25.1875rem;height:14.6250rem;border:none\" src=\".\/images\/ss_results-buttonslossdiagram.png\"\/><\/p>\n\r<p class=\"p_Text\"><span class=\"f_Text\">&nbsp;<\/span><\/p>\n\r<p class=\"p_Note\"><span class=\"f_CHNote\">Note.<\/span><span class=\"f_Note\"> SAM does not display an energy loss diagram for all of the performance models. If you do not see the Losses tab on the Results page, the diagram is not available.<\/span><\/p>\n\r<h4 class=\"p_Heading4\"><span class=\"f_Heading4\">Using the Loss Diagram in your Documents<\/span><\/h4>\n\r<p class=\"p_Text\"><span class=\"f_Text\">SAM includes a copy of the energy loss diagram in <a href=\"reports.html\" class=\"topiclink\">reports<\/a>.<\/span><\/p>\n\r<p class=\"p_Text\"><span class=\"f_Text\">You can also copy the diagram to your clipboard to use in documents using your operating system\'s clipping tool:<\/span><\/p>\n\r<p class=\"p_List\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 1.5000rem;\"><span class=\"f_List\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_List\">In Windows 7, use the Snipping Tool (type &quot;Snip&quot; in the Windows search box). In Windows 7 and older versions of Windows, you can use the Print Screen key to copy an image of your screen to the clipboard.<\/span><\/p>\n\r<p class=\"p_ListLast\" style=\"text-indent: 0; page-break-inside: avoid; padding-left: 1.5000rem; margin-left: 1.5000rem;\"><span class=\"f_List\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_ListLast\">In OS X, press the Command-Shift-4 keys to drag an area on your screen and save it to an image file.<\/span><\/p>"
})
