hmLoadTopic({
hmKeywords:"",
hmTitle:"Main Window",
hmDescription:"After you choose the models for your analysis, SAM displays the main window, which gives you access to the input pages for each case in the project:",
hmPrevLink:"choose_models.html",
hmNextLink:"input_pages.html",
hmParentLink:"getting_started.html",
hmBreadCrumbs:"<a href=\"getting_started.html\">Getting Started<\/a>",
hmTitlePath:"Getting Started > Main Window",
hmHeader:"<h1 class=\"p_Heading1\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_Heading1\">Main Window<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Text\"><span class=\"f_Text\">After you <a href=\"choose_models.html\" class=\"topiclink\">choose the models for your analysis<\/a>, SAM displays the main window, which gives you access to the input pages for each case in the project:<\/span><\/p>\n\r<p class=\"p_Text\" style=\"text-align: center;\"><img alt=\"SS_MainWindow-Inputs\" style=\"margin:0 auto 0 auto;width:50.0000rem;height:33.3125rem;border:none\" src=\".\/images\/ss_mainwindow-inputs.png\"\/><\/p>\n\r<h3 class=\"p_Heading3_atocs_\" style=\"page-break-inside: avoid; page-break-after: avoid; border-top: none; border-right: none; border-left: none;\"><span class=\"f_Heading3_atocs_\">Shortcut Menus<\/span><\/h3>\n\r<p class=\"p_Text\"><span class=\"f_Text\">A <\/span><img alt=\"SS_Button-ContextArrow\" style=\"margin:0;width:1.7500rem;height:1.7500rem;border:none\" src=\".\/images\/ss_button-contextarrow.png\"\/><span class=\"f_ImageCaption\"> <\/span><span class=\"f_Text\">down arrow in SAM indicates a context menu. Click the button to show a list of commands or options:<\/span><\/p>\n\r<p class=\"p_Text\" style=\"text-align: center;\"><img alt=\"SS_ShortcutMenu\" style=\"margin:0 auto 0 auto;width:27.3125rem;height:8.6250rem;border:none\" src=\".\/images\/ss_shortcutmenu.png\"\/><\/p>\n\r<h3 class=\"p_Heading3_atocs_\" style=\"page-break-inside: avoid; page-break-after: avoid; border-top: none; border-right: none; border-left: none;\"><span class=\"f_Heading3_atocs_\">Case Tabs<\/span><\/h3>\n\r<p class=\"p_Text\"><span class=\"f_Text\">The case tab cases in the project and a context menu with commands for <a href=\"manage_cases.html\" class=\"topiclink\">managing cases<\/a>. A project may consist of a single case, or may contain more than one case.<\/span><\/p>\n\r<p class=\"p_Text\" style=\"text-align: center;\"><img alt=\"SS_MainWindow-CaseMenu\" style=\"margin:0 auto 0 auto;width:40.8750rem;height:24.9375rem;border:none\" src=\".\/images\/ss_mainwindow-casemenu.png\"\/><\/p>\n\r<p class=\"p_ListLast\" style=\"page-break-inside: avoid;\"><span class=\"f_ListLast\">&nbsp;<\/span><\/p>\n\r"
})
