hmLoadTopic({
hmKeywords:"",
hmTitle:"Levelized Cost of Storage (LCOS)",
hmDescription:"The levelized cost of storage (LCOS) is the total cost of the battery over its life expressed in cents per kilowatt-hour of electricity discharged by the battery. The LCOS...",
hmPrevLink:"mtf_lcoe.html",
hmNextLink:"mtf_lppa.html",
hmParentLink:"financial_metrics.html",
hmBreadCrumbs:"<a href=\"financial_metrics.html\">Financial Metrics<\/a>",
hmTitlePath:"Financial Metrics > Levelized Cost of Storage (LCOS)",
hmHeader:"<h1 class=\"p_Heading1\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_Heading1\">Levelized Cost of Storage (LCOS)<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Text\"><span class=\"f_Text\">The levelized cost of storage (LCOS) is the total cost of the battery over its life expressed in cents per kilowatt-hour of electricity discharged by the battery. The LCOS takes into account the following:<\/span><\/p>\n\r<p class=\"p_List\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 1.5000rem;\"><span class=\"f_List\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_List\">Cost of installing, maintaining, and replacing the battery.<\/span><\/p>\n\r<p class=\"p_List\" style=\"text-indent: 0; padding-left: 1.5000rem; margin-left: 1.5000rem;\"><span class=\"f_List\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_List\">Cost of electricity to charge the battery.<\/span><\/p>\n\r<p class=\"p_ListLast\" style=\"text-indent: 0; page-break-inside: avoid; padding-left: 1.5000rem; margin-left: 1.5000rem;\"><span class=\"f_List\" style=\"font-family: Arial,\'Lucida Sans Unicode\',\'Lucida Grande\',\'Lucida Sans\';display:inline-block;width:1.5000rem;margin-left:-1.5000rem\">&#8226;<\/span><span class=\"f_ListLast\">Degradation of battery capacity over time.<\/span><\/p>\n\r<p class=\"p_Text\"><span class=\"f_Text\">SAM\'s LCOS calculations are based on the method described in Schmidt, O.; Melchior, S.; Hawkes, A.; Staffel, I. (2019). <a href=\"https:\/\/doi.org\/10.1016\/j.joule.2018.12.008\" target=\"_blank\" class=\"weblink\" title=\"https:\/\/doi.org\/10.1016\/j.joule.2018.12.008\">Projecting the Future Levelized Cost of Electricity Storage Technologies<\/a>. Joule. Vol 3 p 81-100.<\/span><\/p>\n\r<p class=\"p_Text\"><span class=\"f_Text\">For behind-the-meter battery storage applications, the cost of electricity to charge the battery is determined by the retail electricity rates defined on the Electricity Rates page. For front-of-meter applications, the cost depends on the retail rates defined on the Electricity Purchases page.<\/span><\/p>\n\r"
})
