hmLoadTopic({
hmKeywords:"",
hmTitle:"Indifference Point",
hmDescription:"The Third Party - Host \/ Developer financial model calculates the host indifference point, which quantifies host\'s annual electricity bill from the utility without the...",
hmPrevLink:"mtf_revenues.html",
hmNextLink:"mtf_irr.html",
hmParentLink:"financial_metrics.html",
hmBreadCrumbs:"<a href=\"financial_metrics.html\">Financial Metrics<\/a>",
hmTitlePath:"Financial Metrics > Indifference Point",
hmHeader:"<h1 class=\"p_Heading1\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_Heading1\">Indifference Point<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Text\"><span class=\"f_Text\">The <a href=\"fin_tpo_host_developer.html\" class=\"topiclink\">Third Party - Host \/ Developer<\/a> financial model calculates the host indifference point, which quantifies host\'s annual electricity bill from the utility without the renewable energy system as a rate per unit of electricity (\$\/kWh), accounting for the host\'s electricity rate structure and consumption. <\/span><\/p>\n\r<p class=\"p_Text\"><span class=\"f_Text\">The indifference point is the maximum power purchase agreement (PPA) price that makes the PPA more cost effective to the host than purchasing power from the utility: The host is unlikely to accept a PPA if the developer offers a PPA price that is greater than the indifference point. Like the <a href=\"mtf_ppa_price.html\" class=\"topiclink\">PPA price<\/a>, SAM reports the Year 1, nominal levelized, and real levelized indifference point. Be sure to compare the same form of the indifference point and PPA price.<\/span><\/p>\n\r<p class=\"p_Text\"><span class=\"f_Text\">The host indifference point in each year is the <a href=\"mtf_revenues.html\" class=\"topiclink\">electricity savings<\/a> divided by the total renewable energy production:<\/span><\/p>\n\r<p class=\"p_EquationExcel\"><span class=\"f_EquationExcel\">Host Indifference Point in Year n = Electricity Savings in Year n \/ Annual Energy in Year n<\/span><\/p>\n\r<p class=\"p_Text\"><span class=\"f_Text\">The levelized host indifference point is the present value of the annual values.<\/span><\/p>\n\r<p class=\"p_Note\"><span class=\"f_CHNote\">Note.<\/span><span class=\"f_Note\"> The variable name for the indifference point is &quot;NTE,&quot; which stands for &quot;not to exceed&quot; because the indifference point can also be thought of as the value the PPA price is not to exceed.<\/span><\/p>\n\r"
})
