hmLoadTopic({
hmKeywords:"",
hmTitle:"Heat Rate and Thermal Efficiency",
hmDescription:"For biomass power systems, SAM reports the heat rate and thermal efficiency values from the system\'s annual energy value calculated by the performance model, and the biomass...",
hmPrevLink:"mtp_gross_to_net_conv_factor.html",
hmNextLink:"mtp_pump_power.html",
hmParentLink:"performance_metrics.html",
hmBreadCrumbs:"<a href=\"performance_metrics.html\">Performance Metrics<\/a>",
hmTitlePath:"Performance Metrics > Heat Rate and Thermal Efficiency",
hmHeader:"<h1 class=\"p_Heading1\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_Heading1\">Heat Rate and Thermal Efficiency<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Text\"><span class=\"f_Text\">For biomass power systems, SAM reports the heat rate and thermal efficiency values from the system\'s <a href=\"mtp_annual_energy.html\" class=\"topiclink\">annual energy<\/a> value calculated by the performance model, and the biomass feed rate and overall feedstock heating values from the <a href=\"biopower_feedstock.html\" class=\"topiclink\">Feedstock<\/a> page.<\/span><\/p>\n\r<p class=\"p_VariableName\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_VariableName\">Gross Heat Rate, MMBtu\/MWh<\/span><\/p>\n\r<p class=\"p_EquationExcel\"><span class=\"f_EquationExcel\">Gross Heat Rate (MMBtu\/MWh) = <\/span><span class=\"f_EquationExcel\">Dry Biomass Feed Rate (lb\/year)<\/span><span class=\"f_EquationExcel\"> × Average Overall Feedstock HHV (MMBtu\/lb) ÷ Net Annual Energy (MWh\/year)<\/span><\/p>\n\r<p class=\"p_VariableName\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_VariableName\">Net Heat Rate, MMBtu\/MWh<\/span><\/p>\n\r<p class=\"p_EquationExcel\"><span class=\"f_EquationExcel\">Net Heat Rate (MMBtu\/MWh) = <\/span><span class=\"f_EquationExcel\">Dry Biomass Feed Rate (lb\/year)<\/span><span class=\"f_EquationExcel\"> × Average Overall Feedstock LLV (MMBtu\/lb) ÷ Net Annual Energy (MWh\/year)<\/span><\/p>\n\r<p class=\"p_Text\"><span class=\"f_Text\">The dry biomass feed rate is the annual feed rate from the <a href=\"biopower_feedstock.html\" class=\"topiclink\">Feedstock<\/a> page (and also shown as Annual Biomass Usage in the Metrics table) converted from ton\/year to lb\/year (2000 lb = 1 ton), the average overall feedstock heating values are from the Feedstock page, converted from Btu\/lb to MMBtu\/lb (1,000,000 Btu = 1 MMBtu), Net Annual Energy is from the Metrics table.<\/span><\/p>\n\r<p class=\"p_VariableName\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_VariableName\">Thermal Efficiency HHV, %<\/span><\/p>\n\r<p class=\"p_EquationExcel\"><span class=\"f_EquationExcel\">Thermal Efficiency HHV (%) = 341.23 (MMBtu\/MWh) ÷ Gross Heat Rate (MMBtu\/MWh)<\/span><\/p>\n\r<p class=\"p_VariableName\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_VariableName\">Thermal Efficiency LHV, %<\/span><\/p>\n\r<p class=\"p_EquationExcel\"><span class=\"f_EquationExcel\">Thermal Efficiency LHV (%) = 341.23 (MMBtu\/MWh) ÷ Net Heat Rate (MMBtu\/MWh)<\/span><\/p>\n\r<p class=\"p_Text\"><span class=\"f_Text\">Where 341.23 MMBtu\/MWh is the conversion factor between MMBtu and MWh units, and the heat rates are the values described above.<\/span><\/p>\n\r"
})
