hmLoadTopic({
hmKeywords:"",
hmTitle:"Industrial Process Heat",
hmDescription:"Industrial Process Heat (IPH) systems earn revenue through sales of thermal energy at a power price with optional escalation rate.",
hmPrevLink:"tod_factors.html",
hmNextLink:"incentives_and_depreciation.html",
hmParentLink:"revenue.html",
hmBreadCrumbs:"<a href=\"revenue.html\">Revenue<\/a>",
hmTitlePath:"Revenue > Industrial Process Heat",
hmHeader:"<h1 class=\"p_Heading1\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_Heading1\">Industrial Process Heat<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Text\"><span class=\"f_Text\">Industrial Process Heat (IPH) systems earn revenue through sales of thermal energy at a power price with optional escalation rate.<\/span><\/p>\n\r<h4 class=\"p_Heading4\"><span class=\"f_Heading4\">Price of Heat<\/span><\/h4>\n\r<p class=\"p_VariableName\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_VariableName\">PPA price<\/span><\/p>\n\r<p class=\"p_VariableDescription\"><span class=\"f_VariableDescription\">The price in \$\/MMBtu that the project receives for each unit of thermal energy it delivers.<\/span><\/p>\n\r<p class=\"p_VariableName\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_VariableName\">PPA price escalation<\/span><\/p>\n\r<p class=\"p_VariableDescription\"><span class=\"f_VariableDescription\">An escalation rate applied to the PPA price in Year One to calculate the power purchase price in years two and later in the project cash flow.<\/span><\/p>\n\r<p class=\"p_VariableDescription\"><span class=\"f_VariableDescription\">You can also click <\/span><img alt=\"SS_AnnSched-valschedbutton\" style=\"margin:0;width:1.4375rem;height:1.5000rem;border:none\" src=\".\/images\/ss_annsched-valschedbutton.png\"\/><span class=\"f_VariableDescription\"> and then <\/span><span class=\"f_CHInterfaceElement\">Edit<\/span><span class=\"f_VariableDescription\"> to use the <a href=\"edit_data_table_column.html\" class=\"topiclink\">Edit Schedule<\/a> window to enter a different PPA price for each year of the analysis period instead of a single value.<\/span><\/p>\n\r<p class=\"p_VariableDescription\"><span class=\"f_VariableDescription\">SAM does not apply the inflation rate to the PPA price. If you do not specify a PPA price escalation rate, SAM assumes that the same price applies in all years of the analysis period.<\/span><\/p>\n\r<p class=\"p_VariableName\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_VariableName\">IRR target year<\/span><\/p>\n\r<p class=\"p_VariableDescription\"><span class=\"f_VariableDescription\">SAM reports the IRR at the end of the analysis period and the IRR in the target year that you specify. You can use the target year to see what the IRR is in a given year. You can also see the IRR for each year in the <a href=\"cashflow.html\" class=\"topiclink\">cash flow<\/a>. In Specify PPA mode, the IRR target year does not affect the cash flow.<\/span><\/p>\n\r"
})
