hmLoadTopic({
hmKeywords:"",
hmTitle:"Spatial",
hmDescription:"The Spatial tab displays graphs of albedo and ground irradiance data based on the options you specify for albedo on the Location and Resource page for the Detailed Photovoltaic...",
hmPrevLink:"uncertainties.html",
hmNextLink:"notices.html",
hmParentLink:"results.html",
hmBreadCrumbs:"<a href=\"results.html\">Results<\/a>",
hmTitlePath:"Results > Spatial",
hmHeader:"<h1 class=\"p_Heading1\" style=\"page-break-inside: avoid; page-break-after: avoid;\"><span class=\"f_Heading1\">Spatial<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Text\"><span class=\"f_Text\">The Spatial tab displays graphs of albedo and ground irradiance data based on the options you specify for albedo on the <a href=\"pv_location_and_resource.html#albedo\" class=\"topiclink\">Location and Resource<\/a> page for the Detailed Photovoltaic model. It displays a graph for each subarray defined on the <a href=\"pv_system_design.html\" class=\"topiclink\">System Design<\/a> page. &nbsp;This data may be useful for agrivoltaic projects as an estimate of solar energy available for growing crops under and between rows of modules.<\/span><\/p>\n\r<p class=\"p_Note\"><span class=\"f_CHNote\">Note.<\/span><span class=\"f_Note\"> The data displayed in the graphs is also available on the Data Tables tab under <\/span><span class=\"f_CHInterfaceElement\">Matrix Data<\/span><span class=\"f_Note\">.<\/span><\/p>\n\r<p class=\"p_Text\"><span class=\"f_Text\">The spatial array graphs are plots of solar irradiance in W\/m² on the ground and on the rear of modules in the array over Year 1, assuming that modules are arranged in uniform, rectangular rows. The X axis shows the distance from the edge of modules at the front of the row in meters. The Y axis shows time in hours:<\/span><\/p>\n\r<p class=\"p_Text\" style=\"text-align: center;\"><img alt=\"IMG_UtilityRate-month-end-hours\" style=\"margin:0 auto 0 auto;width:8.1875rem;height:16.4375rem;border:none\" src=\".\/images\/img_utilityrate-month-end-hours.png\"\/><\/p>\n\r<p class=\"p_Text\"><span class=\"f_Text\">The Ground Albedo graph for each subarray shows an estimate of the solar resource available on the ground under the photovoltaic modules in the array, assuming a rectangular array with dimensions defined on the <a href=\"pv_shading.html\" class=\"topiclink\">Shading and Layout<\/a> page.<\/span><\/p>\n\r<p class=\"p_Text\"><span class=\"f_Text\">The Ground Irradiance Between Rows graph for each &nbsp;shows an estimate of the solar resource available on the ground in in the space between rows of photovoltaic modules, assuming a rectangular array with row spacing determined by the ground coverage ratio (GCR) on the System Design page.<\/span><\/p>\n\r<p class=\"p_Text\"><span class=\"f_Text\">The Module Rear Irradiance graph for each subarray shows the distribution of irradiance on the back of rows of modules available for bifacial modules based on the spatial albedo inputs on the Location and Resource page.<\/span><\/p>\n\r"
})
