name: Build wxWidgets

on:
  push:
  pull_request:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-ubuntu-1804:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-18.04
    strategy:
        matrix:
            python-version: [ 3.7 ]
            
    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          freeglut3-dev \
          libcurl4-openssl-dev \
          libfontconfig-dev \
          libgl1-mesa-dev \
          libgtk2.0-dev \
          mesa-common-dev \
          unzip

    - name: Get GCC version
      run: gcc --version
    - name: Get libc version
      run: ldd --version

    - name: Install wxWidgets
      run: |
           wget -q https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.5/wxWidgets-3.1.5.tar.bz2
           tar jxf wxWidgets-3.1.5.tar.bz2
           cd wxWidgets-3.1.5
           ./configure --prefix=$HOME/wx-3.1.5 --enable-shared=no --enable-stl=yes --enable-debug=no --with-gtk=2 --with-libjpeg=builtin --with-libpng=builtin --with-regex=builtin --with-libtiff=builtin --with-zlib=builtin --with-expat=builtin --without-libjbig --without-liblzma --without-gtkprint --with-libnotify=no --with-libmspack=no --with-gnomevfs=no --with-opengl=yes --with-sdl=no --with-cxx=11
           make -j2 all install
           sudo ln -s $HOME/wx-3.1.5/bin/wx-config /usr/local/bin/wx-config-3
           ls $HOME/wx-3.1.5/bin
           wx-config-3 --cflags
    
    - name: Test paths
      run: |
        echo "GH workspace:"
        ls ${{env.GITHUB_WORKSPACE}}
        echo "Home:"
        ls ${HOME}/wx-3.1.5
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
          name: wxWidgets Linux
          path: ${{env.GITHUB_WORKSPACE}}/wx-3.1.5/bin/wx-config

  build-mac:
    runs-on: macos-latest
    
    steps:
    - name: Install wxWidgets
      run: |
           wget -q https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.5/wxWidgets-3.1.5.tar.bz2
           tar jxf wxWidgets-3.1.5.tar.bz2
           cd wxWidgets-3.1.5
           ./configure --prefix=$HOME/local/wx-3.1.5/Release --enable-stl=yes --enable-shared=no --disable-debug_flag --with-cocoa --enable-universal_binary=x86_64,arm64 --enable-unicode --enable-webview --disable-mediactrl --with-cxx=11 --with-macosx-version-min=10.15  --with-libjpeg=builtin --with-libpng=builtin --with-regex=builtin --with-libtiff=builtin --with-zlib=builtin --with-expat=builtin
           make clean
           make -j4
           make install
           ln -s $HOME/local/wx-3.1.5/Release/bin/wx-config /usr/local/bin/wx-config-3
           wx-config-3 --cflags
    
    - name: Test paths
      run: |
        echo "GH workspace:"
        ls ${{env.GITHUB_WORKSPACE}}
        echo "Home:"
        ls ${HOME}/local/wx-3.1.5
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
          name: wxWidgets Mac
          path: ${{env.GITHUB_WORKSPACE}}/local/wx-3.1.5/Release/bin/wx-config

